// 4級語彙テーマ別データ (新構築 2026-05-09)
// 20カテゴリ・約690語、4級必須3500語の約20%カバー
// 構造: vi(越), jp(日), pos(品詞), hanviet(漢越), ex_vi(例文越), ex_jp(例文日), note(注釈), cat(テーマ)
// 2語以上の連語は1語彙として登録 (例: "đi học" "công ty")
// 品詞: 名詞/動詞-動作/動詞-状態/形容詞/副詞/前置詞/接続詞/類別詞
var VOCAB_THEMED = [
// === 1. 家族・人間関係 (30) ===
{vi:"gia đình",jp:"家族",pos:"名詞",hanviet:"家庭",ex_vi:"Gia đình tôi có 4 người.",ex_jp:"私の家族は4人です。",note:"",cat:"家族・人間関係"},
{vi:"bố",jp:"父",pos:"名詞",hanviet:"",ex_vi:"Bố tôi là kỹ sư.",ex_jp:"私の父は技師です。",note:"南部はba",cat:"家族・人間関係"},
{vi:"mẹ",jp:"母",pos:"名詞",hanviet:"",ex_vi:"Mẹ đang nấu cơm.",ex_jp:"母が料理をしている。",note:"南部はmá",cat:"家族・人間関係"},
{vi:"con",jp:"子供",pos:"名詞",hanviet:"",ex_vi:"Vợ chồng tôi có hai con.",ex_jp:"私たち夫婦には子供が2人います。",note:"",cat:"家族・人間関係"},
{vi:"con trai",jp:"息子",pos:"名詞",hanviet:"",ex_vi:"Con trai tôi đang học đại học.",ex_jp:"息子は大学で学んでいる。",note:"",cat:"家族・人間関係"},
{vi:"con gái",jp:"娘",pos:"名詞",hanviet:"",ex_vi:"Con gái tôi 5 tuổi.",ex_jp:"娘は5歳です。",note:"",cat:"家族・人間関係"},
{vi:"anh trai",jp:"兄",pos:"名詞",hanviet:"",ex_vi:"Anh trai tôi sống ở Tokyo.",ex_jp:"兄は東京に住んでいる。",note:"",cat:"家族・人間関係"},
{vi:"chị gái",jp:"姉",pos:"名詞",hanviet:"",ex_vi:"Chị gái tôi đã kết hôn.",ex_jp:"姉は結婚した。",note:"",cat:"家族・人間関係"},
{vi:"em trai",jp:"弟",pos:"名詞",hanviet:"",ex_vi:"Em trai tôi rất thích bóng đá.",ex_jp:"弟はサッカーが大好きだ。",note:"",cat:"家族・人間関係"},
{vi:"em gái",jp:"妹",pos:"名詞",hanviet:"",ex_vi:"Em gái tôi học cấp 3.",ex_jp:"妹は高校生だ。",note:"",cat:"家族・人間関係"},
{vi:"ông",jp:"祖父・年配男性",pos:"名詞",hanviet:"",ex_vi:"Ông tôi 80 tuổi.",ex_jp:"祖父は80歳です。",note:"",cat:"家族・人間関係"},
{vi:"bà",jp:"祖母・年配女性",pos:"名詞",hanviet:"",ex_vi:"Bà tôi nấu phở rất ngon.",ex_jp:"祖母はフォーがとても上手だ。",note:"",cat:"家族・人間関係"},
{vi:"cháu",jp:"孫・甥姪",pos:"名詞",hanviet:"",ex_vi:"Bà có 3 cháu.",ex_jp:"祖母には孫が3人いる。",note:"",cat:"家族・人間関係"},
{vi:"vợ",jp:"妻",pos:"名詞",hanviet:"",ex_vi:"Vợ tôi là giáo viên.",ex_jp:"妻は教師です。",note:"",cat:"家族・人間関係"},
{vi:"chồng",jp:"夫",pos:"名詞",hanviet:"",ex_vi:"Chồng tôi đi công tác.",ex_jp:"夫は出張中です。",note:"",cat:"家族・人間関係"},
{vi:"bạn",jp:"友達",pos:"名詞",hanviet:"",ex_vi:"Tôi có nhiều bạn ở Việt Nam.",ex_jp:"ベトナムには友達がたくさんいる。",note:"",cat:"家族・人間関係"},
{vi:"bạn thân",jp:"親友",pos:"名詞",hanviet:"-親",ex_vi:"Cô ấy là bạn thân của tôi.",ex_jp:"彼女は私の親友だ。",note:"",cat:"家族・人間関係"},
{vi:"hàng xóm",jp:"隣人",pos:"名詞",hanviet:"",ex_vi:"Hàng xóm tôi rất tốt.",ex_jp:"近所の人はとても親切だ。",note:"",cat:"家族・人間関係"},
{vi:"người yêu",jp:"恋人",pos:"名詞",hanviet:"人愛",ex_vi:"Người yêu tôi tên là Lan.",ex_jp:"恋人の名前はランです。",note:"",cat:"家族・人間関係"},
{vi:"kết hôn",jp:"結婚する",pos:"動詞-動作",hanviet:"結婚",ex_vi:"Họ sẽ kết hôn vào tháng sau.",ex_jp:"彼らは来月結婚する。",note:"",cat:"家族・人間関係"},
{vi:"ly hôn",jp:"離婚する",pos:"動詞-動作",hanviet:"離婚",ex_vi:"Vợ chồng đó đã ly hôn.",ex_jp:"その夫婦は離婚した。",note:"",cat:"家族・人間関係"},
{vi:"quen",jp:"知り合う・慣れる",pos:"動詞-動作",hanviet:"",ex_vi:"Tôi quen anh ấy từ 5 năm trước.",ex_jp:"5年前から彼と知り合いだ。",note:"",cat:"家族・人間関係"},
{vi:"giúp đỡ",jp:"助ける",pos:"動詞-動作",hanviet:"-",ex_vi:"Anh ấy luôn giúp đỡ tôi.",ex_jp:"彼はいつも私を助けてくれる。",note:"",cat:"家族・人間関係"},
{vi:"chăm sóc",jp:"世話する",pos:"動詞-動作",hanviet:"",ex_vi:"Mẹ chăm sóc các con.",ex_jp:"母は子供たちの世話をする。",note:"",cat:"家族・人間関係"},
{vi:"yêu",jp:"愛する",pos:"動詞-状態",hanviet:"",ex_vi:"Tôi yêu gia đình tôi.",ex_jp:"私は家族を愛している。",note:"",cat:"家族・人間関係"},
{vi:"ghét",jp:"嫌う",pos:"動詞-状態",hanviet:"",ex_vi:"Tôi ghét nói dối.",ex_jp:"嘘を言うのが嫌いだ。",note:"",cat:"家族・人間関係"},
{vi:"tin",jp:"信じる",pos:"動詞-状態",hanviet:"信",ex_vi:"Tôi tin anh ấy.",ex_jp:"私は彼を信じる。",note:"",cat:"家族・人間関係"},
{vi:"tha thứ",jp:"許す",pos:"動詞-動作",hanviet:"",ex_vi:"Mẹ đã tha thứ cho tôi.",ex_jp:"母は私を許してくれた。",note:"",cat:"家族・人間関係"},
{vi:"cãi nhau",jp:"喧嘩する",pos:"動詞-動作",hanviet:"",ex_vi:"Hai anh em cãi nhau.",ex_jp:"兄弟2人が喧嘩した。",note:"",cat:"家族・人間関係"},
{vi:"làm quen",jp:"知り合いになる",pos:"動詞-動作",hanviet:"",ex_vi:"Tôi muốn làm quen với anh.",ex_jp:"あなたと知り合いになりたい。",note:"",cat:"家族・人間関係"},

// === 2. 身体・健康 (50) ===
{vi:"đầu",jp:"頭",pos:"名詞",hanviet:"",ex_vi:"Tôi bị đau đầu.",ex_jp:"頭が痛い。",note:"⚠️đầu tư=投資",cat:"身体・健康"},
{vi:"tóc",jp:"髪",pos:"名詞",hanviet:"",ex_vi:"Tóc cô ấy dài.",ex_jp:"彼女の髪は長い。",note:"",cat:"身体・健康"},
{vi:"mặt",jp:"顔",pos:"名詞",hanviet:"面",ex_vi:"Rửa mặt rồi đi ngủ.",ex_jp:"顔を洗って寝る。",note:"",cat:"身体・健康"},
{vi:"mắt",jp:"目",pos:"名詞",hanviet:"",ex_vi:"Mắt tôi mỏi.",ex_jp:"目が疲れた。",note:"⚠️mất=無くす",cat:"身体・健康"},
{vi:"mũi",jp:"鼻",pos:"名詞",hanviet:"",ex_vi:"Mũi tôi chảy nước.",ex_jp:"鼻水が出る。",note:"",cat:"身体・健康"},
{vi:"miệng",jp:"口",pos:"名詞",hanviet:"",ex_vi:"Há miệng ra.",ex_jp:"口を開けて。",note:"",cat:"身体・健康"},
{vi:"răng",jp:"歯",pos:"名詞",hanviet:"",ex_vi:"Đánh răng trước khi ngủ.",ex_jp:"寝る前に歯を磨く。",note:"",cat:"身体・健康"},
{vi:"lưỡi",jp:"舌",pos:"名詞",hanviet:"",ex_vi:"Lưỡi đỏ.",ex_jp:"舌が赤い。",note:"",cat:"身体・健康"},
{vi:"tai",jp:"耳",pos:"名詞",hanviet:"",ex_vi:"Tai trái nghe không rõ.",ex_jp:"左耳がよく聞こえない。",note:"⚠️tai nạn=事故",cat:"身体・健康"},
{vi:"cổ",jp:"首",pos:"名詞",hanviet:"",ex_vi:"Cổ tôi mỏi.",ex_jp:"首が凝っている。",note:"",cat:"身体・健康"},
{vi:"vai",jp:"肩",pos:"名詞",hanviet:"",ex_vi:"Đau vai.",ex_jp:"肩が痛い。",note:"",cat:"身体・健康"},
{vi:"lưng",jp:"背中",pos:"名詞",hanviet:"",ex_vi:"Đau lưng.",ex_jp:"背中が痛い。",note:"",cat:"身体・健康"},
{vi:"ngực",jp:"胸",pos:"名詞",hanviet:"",ex_vi:"Ngực hơi tức.",ex_jp:"胸が少し苦しい。",note:"",cat:"身体・健康"},
{vi:"bụng",jp:"お腹",pos:"名詞",hanviet:"",ex_vi:"Bụng đói.",ex_jp:"お腹が空いた。",note:"",cat:"身体・健康"},
{vi:"tay",jp:"手・腕",pos:"名詞",hanviet:"",ex_vi:"Rửa tay sạch.",ex_jp:"手をきれいに洗う。",note:"",cat:"身体・健康"},
{vi:"chân",jp:"足",pos:"名詞",hanviet:"",ex_vi:"Chân tôi mỏi.",ex_jp:"足が疲れた。",note:"",cat:"身体・健康"},
{vi:"ngón tay",jp:"指",pos:"名詞",hanviet:"",ex_vi:"Ngón tay nhỏ.",ex_jp:"指が細い。",note:"",cat:"身体・健康"},
{vi:"da",jp:"皮膚",pos:"名詞",hanviet:"",ex_vi:"Da khô.",ex_jp:"肌が乾燥している。",note:"",cat:"身体・健康"},
{vi:"máu",jp:"血",pos:"名詞",hanviet:"",ex_vi:"Bị chảy máu.",ex_jp:"血が出ている。",note:"",cat:"身体・健康"},
{vi:"tim",jp:"心臓",pos:"名詞",hanviet:"",ex_vi:"Tim đập nhanh.",ex_jp:"心臓がドキドキする。",note:"",cat:"身体・健康"},
{vi:"sức khỏe",jp:"健康",pos:"名詞",hanviet:"力康",ex_vi:"Sức khỏe quan trọng nhất.",ex_jp:"健康が一番大事。",note:"",cat:"身体・健康"},
{vi:"bệnh",jp:"病気",pos:"名詞",hanviet:"病",ex_vi:"Tôi bị bệnh hôm qua.",ex_jp:"昨日病気になった。",note:"",cat:"身体・健康"},
{vi:"bệnh viện",jp:"病院",pos:"名詞",hanviet:"病院",ex_vi:"Đi bệnh viện khám.",ex_jp:"病院に診察に行く。",note:"",cat:"身体・健康"},
{vi:"bác sĩ",jp:"医者",pos:"名詞",hanviet:"博士",ex_vi:"Bác sĩ rất giỏi.",ex_jp:"医者はとても上手だ。",note:"",cat:"身体・健康"},
{vi:"y tá",jp:"看護師",pos:"名詞",hanviet:"医士",ex_vi:"Y tá hiền.",ex_jp:"看護師は優しい。",note:"",cat:"身体・健康"},
{vi:"thuốc",jp:"薬",pos:"名詞",hanviet:"",ex_vi:"Uống thuốc đi.",ex_jp:"薬を飲んで。",note:"",cat:"身体・健康"},
{vi:"khám bệnh",jp:"診察する",pos:"動詞-動作",hanviet:"",ex_vi:"Đi khám bệnh.",ex_jp:"診察に行く。",note:"",cat:"身体・健康"},
{vi:"chữa bệnh",jp:"治療する",pos:"動詞-動作",hanviet:"-病",ex_vi:"Bác sĩ chữa bệnh.",ex_jp:"医者が治療する。",note:"",cat:"身体・健康"},
{vi:"đau",jp:"痛い",pos:"形容詞",hanviet:"",ex_vi:"Răng đau.",ex_jp:"歯が痛い。",note:"",cat:"身体・健康"},
{vi:"sốt",jp:"発熱・熱がある",pos:"動詞-状態",hanviet:"",ex_vi:"Em bị sốt cao.",ex_jp:"高熱がある。",note:"",cat:"身体・健康"},
{vi:"ho",jp:"咳",pos:"名詞",hanviet:"",ex_vi:"Ho nhiều.",ex_jp:"咳が多い。",note:"",cat:"身体・健康"},
{vi:"cảm",jp:"風邪",pos:"名詞",hanviet:"感",ex_vi:"Bị cảm.",ex_jp:"風邪をひいた。",note:"",cat:"身体・健康"},
{vi:"mệt",jp:"疲れる",pos:"動詞-状態",hanviet:"",ex_vi:"Tôi mệt quá.",ex_jp:"とても疲れた。",note:"",cat:"身体・健康"},
{vi:"khỏe",jp:"元気",pos:"形容詞",hanviet:"",ex_vi:"Anh có khỏe không?",ex_jp:"元気ですか?",note:"",cat:"身体・健康"},
{vi:"yếu",jp:"弱い",pos:"形容詞",hanviet:"",ex_vi:"Sức khỏe yếu.",ex_jp:"体力が弱い。",note:"",cat:"身体・健康"},
{vi:"ngủ",jp:"寝る",pos:"動詞-動作",hanviet:"",ex_vi:"Ngủ ngon.",ex_jp:"よく眠る。",note:"",cat:"身体・健康"},
{vi:"thức dậy",jp:"起きる",pos:"動詞-動作",hanviet:"",ex_vi:"Tôi thức dậy lúc 6 giờ.",ex_jp:"6時に起きる。",note:"",cat:"身体・健康"},
{vi:"tập thể dục",jp:"運動する",pos:"動詞-動作",hanviet:"-体育",ex_vi:"Tôi tập thể dục mỗi sáng.",ex_jp:"毎朝運動する。",note:"",cat:"身体・健康"},
{vi:"cao",jp:"高い(身長)",pos:"形容詞",hanviet:"高",ex_vi:"Anh ấy cao.",ex_jp:"彼は背が高い。",note:"",cat:"身体・健康"},
{vi:"thấp",jp:"低い",pos:"形容詞",hanviet:"",ex_vi:"Em thấp hơn anh.",ex_jp:"私は彼より背が低い。",note:"",cat:"身体・健康"},
{vi:"béo",jp:"太っている",pos:"形容詞",hanviet:"",ex_vi:"Béo lên rồi.",ex_jp:"太ってきた。",note:"",cat:"身体・健康"},
{vi:"gầy",jp:"痩せている",pos:"形容詞",hanviet:"",ex_vi:"Cô ấy gầy.",ex_jp:"彼女は痩せている。",note:"",cat:"身体・健康"},
{vi:"chóng mặt",jp:"めまい",pos:"動詞-状態",hanviet:"",ex_vi:"Tôi chóng mặt.",ex_jp:"めまいがする。",note:"",cat:"身体・健康"},
{vi:"buồn nôn",jp:"吐き気",pos:"動詞-状態",hanviet:"",ex_vi:"Bị buồn nôn.",ex_jp:"吐き気がする。",note:"",cat:"身体・健康"},
{vi:"đau bụng",jp:"お腹が痛い",pos:"動詞-状態",hanviet:"",ex_vi:"Tôi bị đau bụng.",ex_jp:"お腹が痛い。",note:"",cat:"身体・健康"},
{vi:"viên thuốc",jp:"錠剤",pos:"名詞",hanviet:"員-",ex_vi:"Uống 2 viên thuốc.",ex_jp:"錠剤2錠を飲む。",note:"",cat:"身体・健康"},
{vi:"đơn thuốc",jp:"処方箋",pos:"名詞",hanviet:"単-",ex_vi:"Lấy đơn thuốc.",ex_jp:"処方箋を取る。",note:"",cat:"身体・健康"},
{vi:"tiêm",jp:"注射",pos:"動詞-動作",hanviet:"",ex_vi:"Tiêm phòng.",ex_jp:"予防接種する。",note:"",cat:"身体・健康"},
{vi:"phẫu thuật",jp:"手術",pos:"動詞-動作",hanviet:"",ex_vi:"Phẫu thuật ở bệnh viện.",ex_jp:"病院で手術する。",note:"",cat:"身体・健康"},
{vi:"hồi phục",jp:"回復する",pos:"動詞-動作",hanviet:"回復",ex_vi:"Hồi phục nhanh nhé.",ex_jp:"早く回復してね。",note:"",cat:"身体・健康"},

// === 3. 食事・食べ物 (50) ===
{vi:"ăn",jp:"食べる",pos:"動詞-動作",hanviet:"",ex_vi:"Ăn cơm chưa?",ex_jp:"ご飯食べた?",note:"",cat:"食事・食べ物"},
{vi:"uống",jp:"飲む",pos:"動詞-動作",hanviet:"",ex_vi:"Uống nước.",ex_jp:"水を飲む。",note:"",cat:"食事・食べ物"},
{vi:"cơm",jp:"ご飯",pos:"名詞",hanviet:"",ex_vi:"Một bát cơm.",ex_jp:"ご飯一杯。",note:"",cat:"食事・食べ物"},
{vi:"phở",jp:"フォー",pos:"名詞",hanviet:"",ex_vi:"Tôi thích phở bò.",ex_jp:"牛肉フォーが好き。",note:"",cat:"食事・食べ物"},
{vi:"bún",jp:"ブン(米麺)",pos:"名詞",hanviet:"",ex_vi:"Bún chả Hà Nội.",ex_jp:"ハノイのブンチャー。",note:"",cat:"食事・食べ物"},
{vi:"bánh mì",jp:"バインミー",pos:"名詞",hanviet:"",ex_vi:"Mua bánh mì.",ex_jp:"バインミーを買う。",note:"",cat:"食事・食べ物"},
{vi:"thịt",jp:"肉",pos:"名詞",hanviet:"",ex_vi:"Thịt bò ngon.",ex_jp:"牛肉がおいしい。",note:"",cat:"食事・食べ物"},
{vi:"thịt bò",jp:"牛肉",pos:"名詞",hanviet:"",ex_vi:"Phở thịt bò.",ex_jp:"牛肉のフォー。",note:"",cat:"食事・食べ物"},
{vi:"thịt gà",jp:"鶏肉",pos:"名詞",hanviet:"",ex_vi:"Thịt gà luộc.",ex_jp:"茹で鶏。",note:"",cat:"食事・食べ物"},
{vi:"thịt lợn",jp:"豚肉",pos:"名詞",hanviet:"",ex_vi:"Thịt lợn rán.",ex_jp:"豚肉の唐揚げ。",note:"南部はheo",cat:"食事・食べ物"},
{vi:"cá",jp:"魚",pos:"名詞",hanviet:"",ex_vi:"Cá biển tươi.",ex_jp:"新鮮な海の魚。",note:"",cat:"食事・食べ物"},
{vi:"tôm",jp:"エビ",pos:"名詞",hanviet:"",ex_vi:"Tôm hấp.",ex_jp:"蒸しエビ。",note:"",cat:"食事・食べ物"},
{vi:"trứng",jp:"卵",pos:"名詞",hanviet:"",ex_vi:"Trứng gà.",ex_jp:"鶏卵。",note:"",cat:"食事・食べ物"},
{vi:"rau",jp:"野菜",pos:"名詞",hanviet:"",ex_vi:"Ăn nhiều rau.",ex_jp:"野菜をたくさん食べる。",note:"",cat:"食事・食べ物"},
{vi:"hoa quả",jp:"果物",pos:"名詞",hanviet:"花果",ex_vi:"Mua hoa quả.",ex_jp:"果物を買う。",note:"南部はtrái cây",cat:"食事・食べ物"},
{vi:"chuối",jp:"バナナ",pos:"名詞",hanviet:"",ex_vi:"Một quả chuối.",ex_jp:"バナナ1本。",note:"",cat:"食事・食べ物"},
{vi:"táo",jp:"リンゴ",pos:"名詞",hanviet:"",ex_vi:"Táo đỏ ngon.",ex_jp:"赤いリンゴはおいしい。",note:"",cat:"食事・食べ物"},
{vi:"cam",jp:"オレンジ",pos:"名詞",hanviet:"",ex_vi:"Nước cam tươi.",ex_jp:"フレッシュオレンジジュース。",note:"",cat:"食事・食べ物"},
{vi:"xoài",jp:"マンゴー",pos:"名詞",hanviet:"",ex_vi:"Xoài chín.",ex_jp:"熟したマンゴー。",note:"",cat:"食事・食べ物"},
{vi:"dưa hấu",jp:"スイカ",pos:"名詞",hanviet:"",ex_vi:"Dưa hấu ngọt.",ex_jp:"スイカは甘い。",note:"",cat:"食事・食べ物"},
{vi:"sầu riêng",jp:"ドリアン",pos:"名詞",hanviet:"",ex_vi:"Sầu riêng nặng mùi.",ex_jp:"ドリアンは匂いが強い。",note:"",cat:"食事・食べ物"},
{vi:"đường",jp:"砂糖・道",pos:"名詞",hanviet:"糖",ex_vi:"Cho đường vào cà phê.",ex_jp:"コーヒーに砂糖を入れる。",note:"",cat:"食事・食べ物"},
{vi:"muối",jp:"塩",pos:"名詞",hanviet:"",ex_vi:"Cho thêm muối.",ex_jp:"塩を追加する。",note:"",cat:"食事・食べ物"},
{vi:"nước mắm",jp:"魚醤",pos:"名詞",hanviet:"",ex_vi:"Nước mắm Phú Quốc.",ex_jp:"フーコックの魚醤。",note:"",cat:"食事・食べ物"},
{vi:"tương ớt",jp:"チリソース",pos:"名詞",hanviet:"",ex_vi:"Cay với tương ớt.",ex_jp:"チリソースで辛くする。",note:"",cat:"食事・食べ物"},
{vi:"dầu ăn",jp:"食用油",pos:"名詞",hanviet:"-",ex_vi:"Dầu ăn thực vật.",ex_jp:"植物油。",note:"",cat:"食事・食べ物"},
{vi:"cà phê",jp:"コーヒー",pos:"名詞",hanviet:"",ex_vi:"Một ly cà phê đá.",ex_jp:"アイスコーヒー1杯。",note:"",cat:"食事・食べ物"},
{vi:"trà",jp:"お茶",pos:"名詞",hanviet:"",ex_vi:"Trà nóng.",ex_jp:"熱いお茶。",note:"",cat:"食事・食べ物"},
{vi:"nước",jp:"水",pos:"名詞",hanviet:"",ex_vi:"Uống nước nhiều.",ex_jp:"水をたくさん飲む。",note:"",cat:"食事・食べ物"},
{vi:"bia",jp:"ビール",pos:"名詞",hanviet:"",ex_vi:"Một chai bia.",ex_jp:"ビール1本。",note:"",cat:"食事・食べ物"},
{vi:"rượu",jp:"酒",pos:"名詞",hanviet:"",ex_vi:"Uống rượu vang.",ex_jp:"ワインを飲む。",note:"",cat:"食事・食べ物"},
{vi:"sữa",jp:"牛乳",pos:"名詞",hanviet:"",ex_vi:"Uống sữa mỗi sáng.",ex_jp:"毎朝牛乳を飲む。",note:"",cat:"食事・食べ物"},
{vi:"nấu ăn",jp:"料理する",pos:"動詞-動作",hanviet:"",ex_vi:"Mẹ nấu ăn rất ngon.",ex_jp:"母は料理が上手だ。",note:"",cat:"食事・食べ物"},
{vi:"luộc",jp:"茹でる",pos:"動詞-動作",hanviet:"",ex_vi:"Luộc trứng.",ex_jp:"卵を茹でる。",note:"",cat:"食事・食べ物"},
{vi:"chiên",jp:"揚げる",pos:"動詞-動作",hanviet:"",ex_vi:"Chiên cá.",ex_jp:"魚を揚げる。",note:"南部",cat:"食事・食べ物"},
{vi:"rán",jp:"揚げる",pos:"動詞-動作",hanviet:"",ex_vi:"Rán gà.",ex_jp:"鶏を揚げる。",note:"北部",cat:"食事・食べ物"},
{vi:"nướng",jp:"焼く",pos:"動詞-動作",hanviet:"",ex_vi:"Thịt nướng.",ex_jp:"焼肉。",note:"",cat:"食事・食べ物"},
{vi:"hấp",jp:"蒸す",pos:"動詞-動作",hanviet:"",ex_vi:"Cá hấp.",ex_jp:"蒸し魚。",note:"",cat:"食事・食べ物"},
{vi:"xào",jp:"炒める",pos:"動詞-動作",hanviet:"",ex_vi:"Rau xào.",ex_jp:"野菜炒め。",note:"",cat:"食事・食べ物"},
{vi:"ngon",jp:"おいしい",pos:"形容詞",hanviet:"",ex_vi:"Phở rất ngon.",ex_jp:"フォーはとてもおいしい。",note:"",cat:"食事・食べ物"},
{vi:"ngọt",jp:"甘い",pos:"形容詞",hanviet:"",ex_vi:"Bánh ngọt.",ex_jp:"ケーキは甘い。",note:"",cat:"食事・食べ物"},
{vi:"chua",jp:"酸っぱい",pos:"形容詞",hanviet:"",ex_vi:"Chanh chua.",ex_jp:"レモンは酸っぱい。",note:"",cat:"食事・食べ物"},
{vi:"cay",jp:"辛い",pos:"形容詞",hanviet:"",ex_vi:"Ớt cay.",ex_jp:"唐辛子は辛い。",note:"",cat:"食事・食べ物"},
{vi:"mặn",jp:"塩辛い",pos:"形容詞",hanviet:"",ex_vi:"Canh mặn.",ex_jp:"スープが塩辛い。",note:"",cat:"食事・食べ物"},
{vi:"đắng",jp:"苦い",pos:"形容詞",hanviet:"",ex_vi:"Cà phê đắng.",ex_jp:"コーヒーは苦い。",note:"",cat:"食事・食べ物"},
{vi:"nhạt",jp:"薄い味",pos:"形容詞",hanviet:"",ex_vi:"Canh nhạt.",ex_jp:"スープが薄い。",note:"",cat:"食事・食べ物"},
{vi:"đói",jp:"お腹が空く",pos:"動詞-状態",hanviet:"",ex_vi:"Bụng đói.",ex_jp:"お腹が空いた。",note:"",cat:"食事・食べ物"},
{vi:"no",jp:"満腹",pos:"動詞-状態",hanviet:"",ex_vi:"No rồi.",ex_jp:"もうお腹いっぱい。",note:"",cat:"食事・食べ物"},
{vi:"khát",jp:"喉が渇く",pos:"動詞-状態",hanviet:"",ex_vi:"Tôi khát nước.",ex_jp:"喉が渇いた。",note:"",cat:"食事・食べ物"},
{vi:"nhà hàng",jp:"レストラン",pos:"名詞",hanviet:"",ex_vi:"Nhà hàng đông khách.",ex_jp:"レストランはお客でいっぱい。",note:"",cat:"食事・食べ物"},
{vi:"quán ăn",jp:"食堂",pos:"名詞",hanviet:"館-",ex_vi:"Quán ăn ngon.",ex_jp:"おいしい食堂。",note:"",cat:"食事・食べ物"},

// === 4. 衣服・買い物 (30) ===
{vi:"quần áo",jp:"服(総称)",pos:"名詞",hanviet:"",ex_vi:"Mua quần áo mới.",ex_jp:"新しい服を買う。",note:"",cat:"衣服・買い物"},
{vi:"áo",jp:"上着・シャツ",pos:"名詞",hanviet:"",ex_vi:"Áo trắng.",ex_jp:"白いシャツ。",note:"",cat:"衣服・買い物"},
{vi:"quần",jp:"ズボン",pos:"名詞",hanviet:"",ex_vi:"Quần dài.",ex_jp:"長ズボン。",note:"",cat:"衣服・買い物"},
{vi:"váy",jp:"スカート",pos:"名詞",hanviet:"",ex_vi:"Cô ấy mặc váy.",ex_jp:"彼女はスカートをはいている。",note:"",cat:"衣服・買い物"},
{vi:"giày",jp:"靴",pos:"名詞",hanviet:"",ex_vi:"Đôi giày mới.",ex_jp:"新しい靴。",note:"",cat:"衣服・買い物"},
{vi:"dép",jp:"サンダル",pos:"名詞",hanviet:"",ex_vi:"Dép đi trong nhà.",ex_jp:"室内サンダル。",note:"",cat:"衣服・買い物"},
{vi:"mũ",jp:"帽子",pos:"名詞",hanviet:"",ex_vi:"Đội mũ.",ex_jp:"帽子をかぶる。",note:"",cat:"衣服・買い物"},
{vi:"kính",jp:"眼鏡",pos:"名詞",hanviet:"",ex_vi:"Đeo kính.",ex_jp:"眼鏡をかける。",note:"",cat:"衣服・買い物"},
{vi:"túi xách",jp:"バッグ",pos:"名詞",hanviet:"",ex_vi:"Túi xách đẹp.",ex_jp:"きれいなバッグ。",note:"",cat:"衣服・買い物"},
{vi:"ví",jp:"財布",pos:"名詞",hanviet:"",ex_vi:"Ví da.",ex_jp:"革の財布。",note:"",cat:"衣服・買い物"},
{vi:"đồng hồ",jp:"時計",pos:"名詞",hanviet:"同壷",ex_vi:"Đồng hồ chính xác.",ex_jp:"時計は正確だ。",note:"",cat:"衣服・買い物"},
{vi:"mặc",jp:"着る",pos:"動詞-動作",hanviet:"",ex_vi:"Mặc áo dài.",ex_jp:"アオザイを着る。",note:"",cat:"衣服・買い物"},
{vi:"cởi",jp:"脱ぐ",pos:"動詞-動作",hanviet:"",ex_vi:"Cởi giày trước cửa.",ex_jp:"玄関で靴を脱ぐ。",note:"",cat:"衣服・買い物"},
{vi:"đội",jp:"被る",pos:"動詞-動作",hanviet:"",ex_vi:"Đội nón.",ex_jp:"笠をかぶる。",note:"",cat:"衣服・買い物"},
{vi:"mua",jp:"買う",pos:"動詞-動作",hanviet:"",ex_vi:"Mua hàng.",ex_jp:"買い物する。",note:"",cat:"衣服・買い物"},
{vi:"bán",jp:"売る",pos:"動詞-動作",hanviet:"",ex_vi:"Cửa hàng bán quần áo.",ex_jp:"店は服を売っている。",note:"",cat:"衣服・買い物"},
{vi:"chọn",jp:"選ぶ",pos:"動詞-動作",hanviet:"",ex_vi:"Chọn màu nào?",ex_jp:"どの色を選ぶ?",note:"",cat:"衣服・買い物"},
{vi:"thử",jp:"試す",pos:"動詞-動作",hanviet:"",ex_vi:"Thử áo này.",ex_jp:"この服を試着する。",note:"",cat:"衣服・買い物"},
{vi:"giảm giá",jp:"値引きする",pos:"動詞-動作",hanviet:"減価",ex_vi:"Giảm giá 30%.",ex_jp:"30%値引き。",note:"",cat:"衣服・買い物"},
{vi:"đắt",jp:"高い(値段)",pos:"形容詞",hanviet:"",ex_vi:"Đắt quá.",ex_jp:"高すぎる。",note:"",cat:"衣服・買い物"},
{vi:"rẻ",jp:"安い",pos:"形容詞",hanviet:"",ex_vi:"Rẻ hơn ở chợ.",ex_jp:"市場の方が安い。",note:"",cat:"衣服・買い物"},
{vi:"vừa",jp:"ちょうど(サイズ)",pos:"形容詞",hanviet:"",ex_vi:"Áo này vừa.",ex_jp:"この服はぴったり。",note:"",cat:"衣服・買い物"},
{vi:"rộng",jp:"広い・ゆるい",pos:"形容詞",hanviet:"",ex_vi:"Áo rộng.",ex_jp:"服がゆるい。",note:"",cat:"衣服・買い物"},
{vi:"chật",jp:"きつい",pos:"形容詞",hanviet:"",ex_vi:"Quần chật.",ex_jp:"ズボンがきつい。",note:"",cat:"衣服・買い物"},
{vi:"cửa hàng",jp:"店",pos:"名詞",hanviet:"-項",ex_vi:"Cửa hàng đóng cửa.",ex_jp:"店は閉まっている。",note:"",cat:"衣服・買い物"},
{vi:"siêu thị",jp:"スーパー",pos:"名詞",hanviet:"超市",ex_vi:"Đi siêu thị.",ex_jp:"スーパーに行く。",note:"",cat:"衣服・買い物"},
{vi:"chợ",jp:"市場",pos:"名詞",hanviet:"",ex_vi:"Đi chợ buổi sáng.",ex_jp:"朝市場に行く。",note:"",cat:"衣服・買い物"},
{vi:"hóa đơn",jp:"領収書",pos:"名詞",hanviet:"貨単",ex_vi:"Xin hóa đơn.",ex_jp:"領収書をください。",note:"",cat:"衣服・買い物"},
{vi:"mặc cả",jp:"値切る",pos:"動詞-動作",hanviet:"",ex_vi:"Mặc cả ở chợ.",ex_jp:"市場で値切る。",note:"",cat:"衣服・買い物"},
{vi:"trả lại",jp:"返す",pos:"動詞-動作",hanviet:"",ex_vi:"Trả lại hàng.",ex_jp:"商品を返品する。",note:"",cat:"衣服・買い物"},

// === 5. 住居・家具 (30) ===
{vi:"nhà",jp:"家",pos:"名詞",hanviet:"",ex_vi:"Về nhà.",ex_jp:"家に帰る。",note:"",cat:"住居・家具"},
{vi:"phòng",jp:"部屋",pos:"名詞",hanviet:"房",ex_vi:"Phòng tôi nhỏ.",ex_jp:"私の部屋は小さい。",note:"",cat:"住居・家具"},
{vi:"phòng ngủ",jp:"寝室",pos:"名詞",hanviet:"房-",ex_vi:"Phòng ngủ rộng.",ex_jp:"寝室は広い。",note:"",cat:"住居・家具"},
{vi:"phòng khách",jp:"居間",pos:"名詞",hanviet:"房客",ex_vi:"Phòng khách sạch sẽ.",ex_jp:"居間はきれいだ。",note:"",cat:"住居・家具"},
{vi:"phòng tắm",jp:"浴室",pos:"名詞",hanviet:"房-",ex_vi:"Phòng tắm có vòi sen.",ex_jp:"浴室にシャワーがある。",note:"",cat:"住居・家具"},
{vi:"nhà bếp",jp:"台所",pos:"名詞",hanviet:"-",ex_vi:"Mẹ ở nhà bếp.",ex_jp:"母は台所にいる。",note:"",cat:"住居・家具"},
{vi:"bàn",jp:"机",pos:"名詞",hanviet:"",ex_vi:"Bàn gỗ.",ex_jp:"木の机。",note:"⚠️bán=売る",cat:"住居・家具"},
{vi:"ghế",jp:"椅子",pos:"名詞",hanviet:"",ex_vi:"Ngồi ghế.",ex_jp:"椅子に座る。",note:"",cat:"住居・家具"},
{vi:"giường",jp:"ベッド",pos:"名詞",hanviet:"床",ex_vi:"Giường đôi.",ex_jp:"ダブルベッド。",note:"",cat:"住居・家具"},
{vi:"tủ",jp:"タンス・棚",pos:"名詞",hanviet:"",ex_vi:"Tủ quần áo.",ex_jp:"洋服タンス。",note:"",cat:"住居・家具"},
{vi:"tủ lạnh",jp:"冷蔵庫",pos:"名詞",hanviet:"-冷",ex_vi:"Bia trong tủ lạnh.",ex_jp:"ビールは冷蔵庫の中。",note:"",cat:"住居・家具"},
{vi:"máy giặt",jp:"洗濯機",pos:"名詞",hanviet:"",ex_vi:"Máy giặt mới.",ex_jp:"新しい洗濯機。",note:"",cat:"住居・家具"},
{vi:"máy lạnh",jp:"エアコン",pos:"名詞",hanviet:"",ex_vi:"Bật máy lạnh.",ex_jp:"エアコンをつける。",note:"南部、北部はđiều hòa",cat:"住居・家具"},
{vi:"điều hòa",jp:"エアコン(北部)",pos:"名詞",hanviet:"調和",ex_vi:"Điều hòa hỏng.",ex_jp:"エアコンが壊れた。",note:"",cat:"住居・家具"},
{vi:"quạt",jp:"扇風機",pos:"名詞",hanviet:"",ex_vi:"Quạt máy.",ex_jp:"扇風機。",note:"",cat:"住居・家具"},
{vi:"đèn",jp:"電灯",pos:"名詞",hanviet:"灯",ex_vi:"Bật đèn.",ex_jp:"電灯をつける。",note:"",cat:"住居・家具"},
{vi:"ti vi",jp:"テレビ",pos:"名詞",hanviet:"",ex_vi:"Xem ti vi.",ex_jp:"テレビを見る。",note:"",cat:"住居・家具"},
{vi:"điện thoại",jp:"電話",pos:"名詞",hanviet:"電話",ex_vi:"Gọi điện thoại.",ex_jp:"電話する。",note:"",cat:"住居・家具"},
{vi:"máy tính",jp:"パソコン",pos:"名詞",hanviet:"",ex_vi:"Máy tính của tôi.",ex_jp:"私のパソコン。",note:"",cat:"住居・家具"},
{vi:"cửa",jp:"ドア・扉",pos:"名詞",hanviet:"",ex_vi:"Đóng cửa.",ex_jp:"ドアを閉める。",note:"",cat:"住居・家具"},
{vi:"cửa sổ",jp:"窓",pos:"名詞",hanviet:"",ex_vi:"Mở cửa sổ.",ex_jp:"窓を開ける。",note:"",cat:"住居・家具"},
{vi:"sàn nhà",jp:"床",pos:"名詞",hanviet:"",ex_vi:"Lau sàn nhà.",ex_jp:"床を拭く。",note:"",cat:"住居・家具"},
{vi:"trần",jp:"天井",pos:"名詞",hanviet:"",ex_vi:"Trần cao.",ex_jp:"天井が高い。",note:"",cat:"住居・家具"},
{vi:"chìa khóa",jp:"鍵",pos:"名詞",hanviet:"",ex_vi:"Mất chìa khóa.",ex_jp:"鍵をなくした。",note:"",cat:"住居・家具"},
{vi:"thuê",jp:"借りる(有料)",pos:"動詞-動作",hanviet:"",ex_vi:"Thuê phòng trọ.",ex_jp:"下宿を借りる。",note:"⚠️thuế=税金",cat:"住居・家具"},
{vi:"chuyển nhà",jp:"引っ越す",pos:"動詞-動作",hanviet:"転-",ex_vi:"Chuyển nhà tuần sau.",ex_jp:"来週引っ越す。",note:"",cat:"住居・家具"},
{vi:"sạch",jp:"きれい(清潔)",pos:"形容詞",hanviet:"",ex_vi:"Phòng sạch.",ex_jp:"部屋はきれいだ。",note:"⚠️sách=本",cat:"住居・家具"},
{vi:"bẩn",jp:"汚い",pos:"形容詞",hanviet:"",ex_vi:"Sàn bẩn.",ex_jp:"床が汚い。",note:"",cat:"住居・家具"},
{vi:"dọn dẹp",jp:"片付ける",pos:"動詞-動作",hanviet:"",ex_vi:"Dọn dẹp phòng.",ex_jp:"部屋を片付ける。",note:"",cat:"住居・家具"},
{vi:"trang trí",jp:"装飾する",pos:"動詞-動作",hanviet:"装置",ex_vi:"Trang trí Tết.",ex_jp:"テト(旧正月)に装飾する。",note:"",cat:"住居・家具"},

// === 6. 交通・移動 (30) ===
{vi:"đi",jp:"行く",pos:"動詞-動作",hanviet:"",ex_vi:"Đi đâu?",ex_jp:"どこへ行く?",note:"",cat:"交通・移動"},
{vi:"đến",jp:"着く・来る",pos:"動詞-動作",hanviet:"",ex_vi:"Đến lúc 7 giờ.",ex_jp:"7時に到着する。",note:"",cat:"交通・移動"},
{vi:"về",jp:"帰る",pos:"動詞-動作",hanviet:"",ex_vi:"Về nhà.",ex_jp:"家に帰る。",note:"",cat:"交通・移動"},
{vi:"đi bộ",jp:"歩いて行く",pos:"動詞-動作",hanviet:"-歩",ex_vi:"Đi bộ đến công ty.",ex_jp:"会社まで歩いていく。",note:"",cat:"交通・移動"},
{vi:"chạy",jp:"走る",pos:"動詞-動作",hanviet:"",ex_vi:"Chạy bộ buổi sáng.",ex_jp:"朝ジョギングする。",note:"",cat:"交通・移動"},
{vi:"xe máy",jp:"バイク",pos:"名詞",hanviet:"",ex_vi:"Đi xe máy.",ex_jp:"バイクで行く。",note:"",cat:"交通・移動"},
{vi:"xe đạp",jp:"自転車",pos:"名詞",hanviet:"",ex_vi:"Đạp xe đạp.",ex_jp:"自転車をこぐ。",note:"",cat:"交通・移動"},
{vi:"xe ô tô",jp:"自動車",pos:"名詞",hanviet:"",ex_vi:"Lái xe ô tô.",ex_jp:"車を運転する。",note:"",cat:"交通・移動"},
{vi:"xe buýt",jp:"バス",pos:"名詞",hanviet:"",ex_vi:"Đợi xe buýt.",ex_jp:"バスを待つ。",note:"",cat:"交通・移動"},
{vi:"taxi",jp:"タクシー",pos:"名詞",hanviet:"",ex_vi:"Gọi taxi.",ex_jp:"タクシーを呼ぶ。",note:"",cat:"交通・移動"},
{vi:"tàu hỏa",jp:"電車・列車",pos:"名詞",hanviet:"",ex_vi:"Đi tàu hỏa.",ex_jp:"電車で行く。",note:"",cat:"交通・移動"},
{vi:"máy bay",jp:"飛行機",pos:"名詞",hanviet:"",ex_vi:"Đặt vé máy bay.",ex_jp:"航空券を予約する。",note:"",cat:"交通・移動"},
{vi:"thuyền",jp:"船",pos:"名詞",hanviet:"",ex_vi:"Đi thuyền.",ex_jp:"船で行く。",note:"",cat:"交通・移動"},
{vi:"sân bay",jp:"空港",pos:"名詞",hanviet:"",ex_vi:"Đến sân bay sớm.",ex_jp:"早く空港に着く。",note:"",cat:"交通・移動"},
{vi:"bến xe",jp:"バスターミナル",pos:"名詞",hanviet:"",ex_vi:"Bến xe đông.",ex_jp:"バスターミナルは混む。",note:"",cat:"交通・移動"},
{vi:"ga",jp:"駅",pos:"名詞",hanviet:"",ex_vi:"Ga Hà Nội.",ex_jp:"ハノイ駅。",note:"",cat:"交通・移動"},
{vi:"đường",jp:"道",pos:"名詞",hanviet:"道",ex_vi:"Đường rộng.",ex_jp:"道は広い。",note:"",cat:"交通・移動"},
{vi:"ngã tư",jp:"交差点",pos:"名詞",hanviet:"",ex_vi:"Rẽ phải ở ngã tư.",ex_jp:"交差点で右折。",note:"",cat:"交通・移動"},
{vi:"đèn giao thông",jp:"信号機",pos:"名詞",hanviet:"灯交通",ex_vi:"Đèn đỏ dừng.",ex_jp:"赤信号で止まる。",note:"",cat:"交通・移動"},
{vi:"lái xe",jp:"運転する",pos:"動詞-動作",hanviet:"",ex_vi:"Lái xe cẩn thận.",ex_jp:"気をつけて運転する。",note:"",cat:"交通・移動"},
{vi:"rẽ",jp:"曲がる(北部)",pos:"動詞-動作",hanviet:"",ex_vi:"Rẽ trái.",ex_jp:"左折。",note:"南部はquẹo",cat:"交通・移動"},
{vi:"đi thẳng",jp:"まっすぐ行く",pos:"動詞-動作",hanviet:"",ex_vi:"Đi thẳng 100m.",ex_jp:"100m直進。",note:"",cat:"交通・移動"},
{vi:"dừng",jp:"止まる",pos:"動詞-動作",hanviet:"",ex_vi:"Dừng xe.",ex_jp:"車を止める。",note:"⚠️dùng=使う",cat:"交通・移動"},
{vi:"qua đường",jp:"道を渡る",pos:"動詞-動作",hanviet:"-道",ex_vi:"Qua đường cẩn thận.",ex_jp:"気をつけて道を渡る。",note:"",cat:"交通・移動"},
{vi:"vé",jp:"切符",pos:"名詞",hanviet:"",ex_vi:"Mua vé.",ex_jp:"切符を買う。",note:"",cat:"交通・移動"},
{vi:"hành lý",jp:"荷物",pos:"名詞",hanviet:"行李",ex_vi:"Hành lý nặng.",ex_jp:"荷物が重い。",note:"",cat:"交通・移動"},
{vi:"bản đồ",jp:"地図",pos:"名詞",hanviet:"版図",ex_vi:"Xem bản đồ.",ex_jp:"地図を見る。",note:"",cat:"交通・移動"},
{vi:"tắc đường",jp:"渋滞",pos:"名詞",hanviet:"-道",ex_vi:"Tắc đường giờ cao điểm.",ex_jp:"ラッシュ時に渋滞。",note:"",cat:"交通・移動"},
{vi:"tai nạn",jp:"事故",pos:"名詞",hanviet:"災難",ex_vi:"Bị tai nạn giao thông.",ex_jp:"交通事故にあう。",note:"",cat:"交通・移動"},
{vi:"đến nơi",jp:"目的地に着く",pos:"動詞-動作",hanviet:"-",ex_vi:"Đến nơi rồi.",ex_jp:"着いた。",note:"",cat:"交通・移動"},

// === 7. 数字・お金 (30) ===
{vi:"một",jp:"1",pos:"名詞",hanviet:"",ex_vi:"Một quả táo.",ex_jp:"リンゴ1個。",note:"",cat:"数字・お金"},
{vi:"hai",jp:"2",pos:"名詞",hanviet:"",ex_vi:"Hai người.",ex_jp:"2人。",note:"",cat:"数字・お金"},
{vi:"ba",jp:"3",pos:"名詞",hanviet:"",ex_vi:"Ba ngày.",ex_jp:"3日。",note:"",cat:"数字・お金"},
{vi:"mười",jp:"10",pos:"名詞",hanviet:"",ex_vi:"Mười người.",ex_jp:"10人。",note:"",cat:"数字・お金"},
{vi:"trăm",jp:"100",pos:"名詞",hanviet:"百",ex_vi:"Một trăm nghìn.",ex_jp:"10万(100×千)。",note:"",cat:"数字・お金"},
{vi:"nghìn",jp:"1,000",pos:"名詞",hanviet:"",ex_vi:"Một nghìn đồng.",ex_jp:"1,000ドン。",note:"南部はngàn",cat:"数字・お金"},
{vi:"triệu",jp:"1,000,000",pos:"名詞",hanviet:"兆",ex_vi:"Một triệu đồng.",ex_jp:"100万ドン。",note:"",cat:"数字・お金"},
{vi:"tiền",jp:"お金",pos:"名詞",hanviet:"銭",ex_vi:"Có nhiều tiền.",ex_jp:"お金がたくさんある。",note:"",cat:"数字・お金"},
{vi:"đồng",jp:"ドン(通貨)",pos:"名詞",hanviet:"銅",ex_vi:"50.000 đồng.",ex_jp:"5万ドン。",note:"",cat:"数字・お金"},
{vi:"yên",jp:"円(通貨)",pos:"名詞",hanviet:"円",ex_vi:"100 yên Nhật.",ex_jp:"日本円100円。",note:"",cat:"数字・お金"},
{vi:"đô la",jp:"ドル",pos:"名詞",hanviet:"",ex_vi:"100 đô la Mỹ.",ex_jp:"米ドル100。",note:"",cat:"数字・お金"},
{vi:"giá",jp:"値段",pos:"名詞",hanviet:"価",ex_vi:"Giá bao nhiêu?",ex_jp:"値段はいくら?",note:"⚠️già=年老い",cat:"数字・お金"},
{vi:"tiền mặt",jp:"現金",pos:"名詞",hanviet:"銭面",ex_vi:"Trả tiền mặt.",ex_jp:"現金で払う。",note:"",cat:"数字・お金"},
{vi:"thẻ",jp:"カード",pos:"名詞",hanviet:"",ex_vi:"Thẻ tín dụng.",ex_jp:"クレジットカード。",note:"",cat:"数字・お金"},
{vi:"ngân hàng",jp:"銀行",pos:"名詞",hanviet:"銀行",ex_vi:"Đến ngân hàng.",ex_jp:"銀行に行く。",note:"",cat:"数字・お金"},
{vi:"rút tiền",jp:"お金を引き出す",pos:"動詞-動作",hanviet:"-銭",ex_vi:"Rút tiền ATM.",ex_jp:"ATMで引き出す。",note:"",cat:"数字・お金"},
{vi:"gửi tiền",jp:"お金を預ける",pos:"動詞-動作",hanviet:"-銭",ex_vi:"Gửi tiền vào ngân hàng.",ex_jp:"銀行に預金する。",note:"",cat:"数字・お金"},
{vi:"trả tiền",jp:"支払う",pos:"動詞-動作",hanviet:"-銭",ex_vi:"Trả tiền cà phê.",ex_jp:"コーヒー代を払う。",note:"",cat:"数字・お金"},
{vi:"đổi tiền",jp:"両替する",pos:"動詞-動作",hanviet:"-銭",ex_vi:"Đổi tiền yên sang đồng.",ex_jp:"円をドンに両替する。",note:"",cat:"数字・お金"},
{vi:"nhiều",jp:"多い",pos:"形容詞",hanviet:"",ex_vi:"Nhiều người.",ex_jp:"多くの人。",note:"",cat:"数字・お金"},
{vi:"ít",jp:"少ない",pos:"形容詞",hanviet:"",ex_vi:"Ít tiền.",ex_jp:"お金が少ない。",note:"",cat:"数字・お金"},
{vi:"tăng",jp:"増える",pos:"動詞-動作",hanviet:"増",ex_vi:"Giá tăng.",ex_jp:"値段が上がる。",note:"⚠️tặng=贈る",cat:"数字・お金"},
{vi:"giảm",jp:"減る",pos:"動詞-動作",hanviet:"減",ex_vi:"Giảm 10%.",ex_jp:"10%減。",note:"",cat:"数字・お金"},
{vi:"tổng cộng",jp:"合計",pos:"名詞",hanviet:"総共",ex_vi:"Tổng cộng 500.000 đồng.",ex_jp:"合計50万ドン。",note:"",cat:"数字・お金"},
{vi:"phần trăm",jp:"パーセント",pos:"名詞",hanviet:"分百",ex_vi:"50 phần trăm.",ex_jp:"50%。",note:"",cat:"数字・お金"},
{vi:"đếm",jp:"数える",pos:"動詞-動作",hanviet:"",ex_vi:"Đếm tiền.",ex_jp:"お金を数える。",note:"",cat:"数字・お金"},
{vi:"tính toán",jp:"計算する",pos:"動詞-動作",hanviet:"算-",ex_vi:"Tính toán chi phí.",ex_jp:"費用を計算する。",note:"",cat:"数字・お金"},
{vi:"tiết kiệm",jp:"節約する",pos:"動詞-動作",hanviet:"節検",ex_vi:"Tiết kiệm tiền.",ex_jp:"お金を節約する。",note:"",cat:"数字・お金"},
{vi:"vay",jp:"借りる(お金)",pos:"動詞-動作",hanviet:"",ex_vi:"Vay tiền ngân hàng.",ex_jp:"銀行からお金を借りる。",note:"",cat:"数字・お金"},
{vi:"tỷ",jp:"10億",pos:"名詞",hanviet:"",ex_vi:"Một tỷ đồng.",ex_jp:"10億ドン。",note:"",cat:"数字・お金"},

// === 8. 教育・学校 (30) ===
{vi:"trường học",jp:"学校",pos:"名詞",hanviet:"場学",ex_vi:"Trường học gần nhà.",ex_jp:"学校は家の近く。",note:"",cat:"教育・学校"},
{vi:"đại học",jp:"大学",pos:"名詞",hanviet:"大学",ex_vi:"Đại học Quốc gia.",ex_jp:"国立大学。",note:"",cat:"教育・学校"},
{vi:"lớp",jp:"クラス・学年",pos:"名詞",hanviet:"",ex_vi:"Lớp 10.",ex_jp:"10年生(高校1年)。",note:"",cat:"教育・学校"},
{vi:"học sinh",jp:"生徒",pos:"名詞",hanviet:"学生",ex_vi:"Học sinh chăm chỉ.",ex_jp:"生徒は勤勉だ。",note:"",cat:"教育・学校"},
{vi:"sinh viên",jp:"大学生",pos:"名詞",hanviet:"生員",ex_vi:"Sinh viên năm thứ 3.",ex_jp:"大学3年生。",note:"",cat:"教育・学校"},
{vi:"giáo viên",jp:"教師",pos:"名詞",hanviet:"教員",ex_vi:"Giáo viên tiếng Anh.",ex_jp:"英語教師。",note:"",cat:"教育・学校"},
{vi:"thầy giáo",jp:"男性教師",pos:"名詞",hanviet:"-教",ex_vi:"Thầy giáo trẻ.",ex_jp:"若い男性教師。",note:"",cat:"教育・学校"},
{vi:"cô giáo",jp:"女性教師",pos:"名詞",hanviet:"-教",ex_vi:"Cô giáo hiền.",ex_jp:"女性教師は優しい。",note:"",cat:"教育・学校"},
{vi:"học",jp:"学ぶ",pos:"動詞-動作",hanviet:"学",ex_vi:"Học tiếng Việt.",ex_jp:"ベトナム語を学ぶ。",note:"",cat:"教育・学校"},
{vi:"dạy",jp:"教える",pos:"動詞-動作",hanviet:"",ex_vi:"Dạy tiếng Nhật.",ex_jp:"日本語を教える。",note:"⚠️dậy=起きる",cat:"教育・学校"},
{vi:"đi học",jp:"学校に行く",pos:"動詞-動作",hanviet:"",ex_vi:"Hôm nay tôi đi học.",ex_jp:"今日は学校へ行く。",note:"",cat:"教育・学校"},
{vi:"giảng dạy",jp:"講義する",pos:"動詞-動作",hanviet:"講-",ex_vi:"Giáo sư giảng dạy.",ex_jp:"教授が講義する。",note:"",cat:"教育・学校"},
{vi:"môn học",jp:"科目",pos:"名詞",hanviet:"門学",ex_vi:"Môn học yêu thích.",ex_jp:"好きな科目。",note:"",cat:"教育・学校"},
{vi:"tiếng Anh",jp:"英語",pos:"名詞",hanviet:"-",ex_vi:"Học tiếng Anh.",ex_jp:"英語を学ぶ。",note:"",cat:"教育・学校"},
{vi:"tiếng Nhật",jp:"日本語",pos:"名詞",hanviet:"-日",ex_vi:"Tiếng Nhật khó.",ex_jp:"日本語は難しい。",note:"",cat:"教育・学校"},
{vi:"tiếng Việt",jp:"ベトナム語",pos:"名詞",hanviet:"-越",ex_vi:"Học tiếng Việt 2 năm.",ex_jp:"ベトナム語2年学んだ。",note:"",cat:"教育・学校"},
{vi:"toán",jp:"数学",pos:"名詞",hanviet:"算",ex_vi:"Học toán giỏi.",ex_jp:"数学が得意だ。",note:"",cat:"教育・学校"},
{vi:"lịch sử",jp:"歴史",pos:"名詞",hanviet:"暦史",ex_vi:"Lịch sử Việt Nam.",ex_jp:"ベトナムの歴史。",note:"",cat:"教育・学校"},
{vi:"sách",jp:"本",pos:"名詞",hanviet:"",ex_vi:"Đọc sách.",ex_jp:"本を読む。",note:"⚠️sạch=清潔",cat:"教育・学校"},
{vi:"vở",jp:"ノート",pos:"名詞",hanviet:"",ex_vi:"Viết vào vở.",ex_jp:"ノートに書く。",note:"",cat:"教育・学校"},
{vi:"bút",jp:"ペン",pos:"名詞",hanviet:"筆",ex_vi:"Cây bút mới.",ex_jp:"新しいペン。",note:"",cat:"教育・学校"},
{vi:"bài tập",jp:"宿題・課題",pos:"名詞",hanviet:"-集",ex_vi:"Làm bài tập.",ex_jp:"宿題をする。",note:"",cat:"教育・学校"},
{vi:"thi",jp:"試験を受ける",pos:"動詞-動作",hanviet:"試",ex_vi:"Thi tiếng Việt.",ex_jp:"ベトナム語の試験を受ける。",note:"",cat:"教育・学校"},
{vi:"kỳ thi",jp:"試験",pos:"名詞",hanviet:"期試",ex_vi:"Kỳ thi cuối kỳ.",ex_jp:"期末試験。",note:"",cat:"教育・学校"},
{vi:"đỗ",jp:"合格する",pos:"動詞-動作",hanviet:"",ex_vi:"Đỗ đại học.",ex_jp:"大学に合格する。",note:"",cat:"教育・学校"},
{vi:"trượt",jp:"落ちる(試験)",pos:"動詞-動作",hanviet:"",ex_vi:"Trượt thi.",ex_jp:"試験に落ちる。",note:"",cat:"教育・学校"},
{vi:"điểm",jp:"点数",pos:"名詞",hanviet:"点",ex_vi:"Được 9 điểm.",ex_jp:"9点取った。",note:"",cat:"教育・学校"},
{vi:"chăm chỉ",jp:"勤勉な",pos:"形容詞",hanviet:"",ex_vi:"Học chăm chỉ.",ex_jp:"熱心に勉強する。",note:"",cat:"教育・学校"},
{vi:"lười",jp:"怠惰な",pos:"形容詞",hanviet:"",ex_vi:"Lười học.",ex_jp:"勉強嫌い。",note:"",cat:"教育・学校"},
{vi:"hiểu",jp:"理解する",pos:"動詞-状態",hanviet:"",ex_vi:"Tôi hiểu.",ex_jp:"分かりました。",note:"",cat:"教育・学校"},

// === 9. 仕事・職場 (30) ===
{vi:"công việc",jp:"仕事",pos:"名詞",hanviet:"公役",ex_vi:"Công việc nhiều.",ex_jp:"仕事が多い。",note:"",cat:"仕事・職場"},
{vi:"làm việc",jp:"働く",pos:"動詞-動作",hanviet:"-役",ex_vi:"Làm việc 8 tiếng.",ex_jp:"8時間働く。",note:"",cat:"仕事・職場"},
{vi:"công ty",jp:"会社",pos:"名詞",hanviet:"公司",ex_vi:"Công ty Nhật.",ex_jp:"日系企業。",note:"",cat:"仕事・職場"},
{vi:"văn phòng",jp:"オフィス",pos:"名詞",hanviet:"文房",ex_vi:"Văn phòng tầng 5.",ex_jp:"オフィスは5階。",note:"",cat:"仕事・職場"},
{vi:"giám đốc",jp:"社長・部長",pos:"名詞",hanviet:"監督",ex_vi:"Giám đốc đang họp.",ex_jp:"社長は会議中。",note:"",cat:"仕事・職場"},
{vi:"trưởng phòng",jp:"部長・課長",pos:"名詞",hanviet:"長房",ex_vi:"Trưởng phòng kinh doanh.",ex_jp:"営業部長。",note:"",cat:"仕事・職場"},
{vi:"nhân viên",jp:"従業員",pos:"名詞",hanviet:"人員",ex_vi:"200 nhân viên.",ex_jp:"200人の従業員。",note:"",cat:"仕事・職場"},
{vi:"đồng nghiệp",jp:"同僚",pos:"名詞",hanviet:"同業",ex_vi:"Đồng nghiệp tốt.",ex_jp:"同僚は親切。",note:"",cat:"仕事・職場"},
{vi:"khách hàng",jp:"顧客",pos:"名詞",hanviet:"客項",ex_vi:"Phục vụ khách hàng.",ex_jp:"お客様にサービスする。",note:"",cat:"仕事・職場"},
{vi:"đối tác",jp:"取引先",pos:"名詞",hanviet:"対作",ex_vi:"Đối tác Nhật.",ex_jp:"日本の取引先。",note:"",cat:"仕事・職場"},
{vi:"hợp đồng",jp:"契約",pos:"名詞",hanviet:"合同",ex_vi:"Ký hợp đồng.",ex_jp:"契約を結ぶ。",note:"",cat:"仕事・職場"},
{vi:"họp",jp:"会議をする",pos:"動詞-動作",hanviet:"合",ex_vi:"Họp lúc 9 giờ.",ex_jp:"9時に会議。",note:"",cat:"仕事・職場"},
{vi:"cuộc họp",jp:"会議(回)",pos:"名詞",hanviet:"局合",ex_vi:"Cuộc họp dài.",ex_jp:"会議が長い。",note:"",cat:"仕事・職場"},
{vi:"báo cáo",jp:"報告(する)",pos:"動詞-動作",hanviet:"報告",ex_vi:"Báo cáo tuần.",ex_jp:"週報。",note:"",cat:"仕事・職場"},
{vi:"tài liệu",jp:"資料",pos:"名詞",hanviet:"才料",ex_vi:"Tài liệu họp.",ex_jp:"会議資料。",note:"",cat:"仕事・職場"},
{vi:"dự án",jp:"プロジェクト",pos:"名詞",hanviet:"予案",ex_vi:"Dự án mới.",ex_jp:"新プロジェクト。",note:"",cat:"仕事・職場"},
{vi:"lương",jp:"給料",pos:"名詞",hanviet:"糧",ex_vi:"Lương cao.",ex_jp:"給料が高い。",note:"⚠️lượng=量",cat:"仕事・職場"},
{vi:"thưởng",jp:"ボーナス",pos:"名詞",hanviet:"賞",ex_vi:"Thưởng cuối năm.",ex_jp:"年末ボーナス。",note:"",cat:"仕事・職場"},
{vi:"nghỉ phép",jp:"休暇を取る",pos:"動詞-動作",hanviet:"-法",ex_vi:"Nghỉ phép 3 ngày.",ex_jp:"3日休暇。",note:"",cat:"仕事・職場"},
{vi:"làm thêm giờ",jp:"残業する",pos:"動詞-動作",hanviet:"",ex_vi:"Hôm nay làm thêm giờ.",ex_jp:"今日残業。",note:"",cat:"仕事・職場"},
{vi:"đi công tác",jp:"出張する",pos:"動詞-動作",hanviet:"-公作",ex_vi:"Đi công tác Sài Gòn.",ex_jp:"サイゴンへ出張。",note:"",cat:"仕事・職場"},
{vi:"tuyển dụng",jp:"採用する",pos:"動詞-動作",hanviet:"選用",ex_vi:"Tuyển dụng nhân sự.",ex_jp:"人材を採用。",note:"",cat:"仕事・職場"},
{vi:"phỏng vấn",jp:"面接",pos:"動詞-動作",hanviet:"訪問",ex_vi:"Phỏng vấn thứ 6.",ex_jp:"金曜面接。",note:"",cat:"仕事・職場"},
{vi:"nghỉ việc",jp:"退職する",pos:"動詞-動作",hanviet:"-役",ex_vi:"Nghỉ việc tháng trước.",ex_jp:"先月退職。",note:"",cat:"仕事・職場"},
{vi:"sản phẩm",jp:"製品",pos:"名詞",hanviet:"産品",ex_vi:"Sản phẩm mới.",ex_jp:"新製品。",note:"",cat:"仕事・職場"},
{vi:"dịch vụ",jp:"サービス",pos:"名詞",hanviet:"訳務",ex_vi:"Dịch vụ tốt.",ex_jp:"良いサービス。",note:"",cat:"仕事・職場"},
{vi:"thị trường",jp:"市場",pos:"名詞",hanviet:"市場",ex_vi:"Thị trường mở rộng.",ex_jp:"市場が拡大する。",note:"",cat:"仕事・職場"},
{vi:"quản lý",jp:"管理する",pos:"動詞-動作",hanviet:"管理",ex_vi:"Quản lý nhân viên.",ex_jp:"従業員を管理する。",note:"",cat:"仕事・職場"},
{vi:"kế hoạch",jp:"計画",pos:"名詞",hanviet:"計画",ex_vi:"Kế hoạch năm.",ex_jp:"年間計画。",note:"",cat:"仕事・職場"},
{vi:"hoàn thành",jp:"達成・完成する",pos:"動詞-動作",hanviet:"完成",ex_vi:"Hoàn thành công việc.",ex_jp:"仕事を完成する。",note:"",cat:"仕事・職場"},

// === 10. 趣味・娯楽 (30) ===
{vi:"sở thích",jp:"趣味",pos:"名詞",hanviet:"所適",ex_vi:"Sở thích của tôi.",ex_jp:"私の趣味。",note:"",cat:"趣味・娯楽"},
{vi:"đọc sách",jp:"読書する",pos:"動詞-動作",hanviet:"-",ex_vi:"Tôi thích đọc sách.",ex_jp:"読書が好き。",note:"",cat:"趣味・娯楽"},
{vi:"xem phim",jp:"映画を見る",pos:"動詞-動作",hanviet:"",ex_vi:"Xem phim cuối tuần.",ex_jp:"週末映画を見る。",note:"",cat:"趣味・娯楽"},
{vi:"nghe nhạc",jp:"音楽を聴く",pos:"動詞-動作",hanviet:"",ex_vi:"Nghe nhạc thư giãn.",ex_jp:"音楽でリラックス。",note:"",cat:"趣味・娯楽"},
{vi:"hát",jp:"歌う",pos:"動詞-動作",hanviet:"",ex_vi:"Hát karaoke.",ex_jp:"カラオケで歌う。",note:"",cat:"趣味・娯楽"},
{vi:"nhảy",jp:"踊る・跳ぶ",pos:"動詞-動作",hanviet:"",ex_vi:"Nhảy múa.",ex_jp:"ダンスする。",note:"",cat:"趣味・娯楽"},
{vi:"chụp ảnh",jp:"写真を撮る",pos:"動詞-動作",hanviet:"-影",ex_vi:"Chụp ảnh kỷ niệm.",ex_jp:"記念写真を撮る。",note:"",cat:"趣味・娯楽"},
{vi:"vẽ",jp:"絵を描く",pos:"動詞-動作",hanviet:"",ex_vi:"Vẽ tranh.",ex_jp:"絵を描く。",note:"",cat:"趣味・娯楽"},
{vi:"chơi",jp:"遊ぶ・(楽器/スポーツを)する",pos:"動詞-動作",hanviet:"",ex_vi:"Chơi với bạn.",ex_jp:"友達と遊ぶ。",note:"",cat:"趣味・娯楽"},
{vi:"trò chơi",jp:"ゲーム",pos:"名詞",hanviet:"-",ex_vi:"Chơi trò chơi điện tử.",ex_jp:"ビデオゲームをする。",note:"",cat:"趣味・娯楽"},
{vi:"phim",jp:"映画",pos:"名詞",hanviet:"",ex_vi:"Phim Hàn Quốc.",ex_jp:"韓国映画。",note:"",cat:"趣味・娯楽"},
{vi:"nhạc",jp:"音楽",pos:"名詞",hanviet:"楽",ex_vi:"Nhạc cổ điển.",ex_jp:"クラシック音楽。",note:"",cat:"趣味・娯楽"},
{vi:"bài hát",jp:"歌",pos:"名詞",hanviet:"-",ex_vi:"Bài hát yêu thích.",ex_jp:"好きな歌。",note:"",cat:"趣味・娯楽"},
{vi:"truyện",jp:"小説・物語",pos:"名詞",hanviet:"伝",ex_vi:"Truyện cổ tích.",ex_jp:"おとぎ話。",note:"",cat:"趣味・娯楽"},
{vi:"du lịch",jp:"旅行",pos:"名詞",hanviet:"遊歴",ex_vi:"Đi du lịch Đà Nẵng.",ex_jp:"ダナンへ旅行。",note:"",cat:"趣味・娯楽"},
{vi:"đi chơi",jp:"遊びに行く",pos:"動詞-動作",hanviet:"",ex_vi:"Đi chơi cuối tuần.",ex_jp:"週末遊びに行く。",note:"",cat:"趣味・娯楽"},
{vi:"thể thao",jp:"スポーツ",pos:"名詞",hanviet:"体操",ex_vi:"Tôi thích thể thao.",ex_jp:"スポーツが好き。",note:"",cat:"趣味・娯楽"},
{vi:"bóng đá",jp:"サッカー",pos:"名詞",hanviet:"-",ex_vi:"Xem bóng đá.",ex_jp:"サッカーを見る。",note:"",cat:"趣味・娯楽"},
{vi:"bóng rổ",jp:"バスケットボール",pos:"名詞",hanviet:"-",ex_vi:"Chơi bóng rổ.",ex_jp:"バスケをする。",note:"",cat:"趣味・娯楽"},
{vi:"bơi",jp:"泳ぐ",pos:"動詞-動作",hanviet:"",ex_vi:"Bơi ở bể bơi.",ex_jp:"プールで泳ぐ。",note:"",cat:"趣味・娯楽"},
{vi:"chạy bộ",jp:"ジョギング",pos:"動詞-動作",hanviet:"-歩",ex_vi:"Chạy bộ buổi sáng.",ex_jp:"朝ジョギング。",note:"",cat:"趣味・娯楽"},
{vi:"yoga",jp:"ヨガ",pos:"名詞",hanviet:"",ex_vi:"Tập yoga.",ex_jp:"ヨガをする。",note:"",cat:"趣味・娯楽"},
{vi:"đi dạo",jp:"散歩する",pos:"動詞-動作",hanviet:"",ex_vi:"Đi dạo công viên.",ex_jp:"公園を散歩。",note:"",cat:"趣味・娯楽"},
{vi:"câu cá",jp:"釣りする",pos:"動詞-動作",hanviet:"",ex_vi:"Đi câu cá.",ex_jp:"釣りに行く。",note:"",cat:"趣味・娯楽"},
{vi:"leo núi",jp:"登山",pos:"動詞-動作",hanviet:"",ex_vi:"Leo núi Phú Sĩ.",ex_jp:"富士山に登る。",note:"",cat:"趣味・娯楽"},
{vi:"vui",jp:"楽しい",pos:"形容詞",hanviet:"",ex_vi:"Hôm nay vui.",ex_jp:"今日は楽しい。",note:"",cat:"趣味・娯楽"},
{vi:"chán",jp:"つまらない",pos:"形容詞",hanviet:"",ex_vi:"Phim chán.",ex_jp:"映画はつまらない。",note:"",cat:"趣味・娯楽"},
{vi:"thú vị",jp:"面白い",pos:"形容詞",hanviet:"趣味",ex_vi:"Sách thú vị.",ex_jp:"本が面白い。",note:"",cat:"趣味・娯楽"},
{vi:"thư giãn",jp:"リラックスする",pos:"動詞-動作",hanviet:"",ex_vi:"Cần thư giãn.",ex_jp:"リラックスが必要。",note:"",cat:"趣味・娯楽"},
{vi:"công viên",jp:"公園",pos:"名詞",hanviet:"公園",ex_vi:"Đi công viên.",ex_jp:"公園に行く。",note:"",cat:"趣味・娯楽"},

// === 11. 自然・天気 (40) ===
{vi:"thời tiết",jp:"天気",pos:"名詞",hanviet:"時節",ex_vi:"Thời tiết đẹp.",ex_jp:"天気が良い。",note:"",cat:"自然・天気"},
{vi:"khí hậu",jp:"気候",pos:"名詞",hanviet:"気候",ex_vi:"Khí hậu nhiệt đới.",ex_jp:"熱帯気候。",note:"",cat:"自然・天気"},
{vi:"nhiệt độ",jp:"気温",pos:"名詞",hanviet:"熱度",ex_vi:"Nhiệt độ 30 độ.",ex_jp:"気温30度。",note:"",cat:"自然・天気"},
{vi:"trời",jp:"空・天",pos:"名詞",hanviet:"",ex_vi:"Trời xanh.",ex_jp:"空が青い。",note:"",cat:"自然・天気"},
{vi:"mặt trời",jp:"太陽",pos:"名詞",hanviet:"面-",ex_vi:"Mặt trời mọc.",ex_jp:"太陽が昇る。",note:"",cat:"自然・天気"},
{vi:"mặt trăng",jp:"月",pos:"名詞",hanviet:"面-",ex_vi:"Mặt trăng tròn.",ex_jp:"月が満ちる。",note:"",cat:"自然・天気"},
{vi:"sao",jp:"星",pos:"名詞",hanviet:"",ex_vi:"Sao sáng.",ex_jp:"星が光る。",note:"",cat:"自然・天気"},
{vi:"mây",jp:"雲",pos:"名詞",hanviet:"",ex_vi:"Trời nhiều mây.",ex_jp:"曇り空。",note:"",cat:"自然・天気"},
{vi:"mưa",jp:"雨",pos:"名詞",hanviet:"",ex_vi:"Trời mưa to.",ex_jp:"大雨だ。",note:"⚠️mua=買う",cat:"自然・天気"},
{vi:"gió",jp:"風",pos:"名詞",hanviet:"",ex_vi:"Gió mạnh.",ex_jp:"風が強い。",note:"",cat:"自然・天気"},
{vi:"bão",jp:"台風",pos:"名詞",hanviet:"",ex_vi:"Bão số 5.",ex_jp:"台風5号。",note:"",cat:"自然・天気"},
{vi:"tuyết",jp:"雪",pos:"名詞",hanviet:"",ex_vi:"Tuyết rơi.",ex_jp:"雪が降る。",note:"⚠️tuyệt=絶対",cat:"自然・天気"},
{vi:"sương mù",jp:"霧",pos:"名詞",hanviet:"",ex_vi:"Sương mù dày.",ex_jp:"霧が濃い。",note:"",cat:"自然・天気"},
{vi:"sấm",jp:"雷鳴",pos:"名詞",hanviet:"",ex_vi:"Có sấm.",ex_jp:"雷が鳴る。",note:"",cat:"自然・天気"},
{vi:"sét",jp:"稲妻",pos:"名詞",hanviet:"",ex_vi:"Sét đánh.",ex_jp:"雷が落ちる。",note:"",cat:"自然・天気"},
{vi:"cầu vồng",jp:"虹",pos:"名詞",hanviet:"",ex_vi:"Cầu vồng đẹp.",ex_jp:"虹が綺麗。",note:"",cat:"自然・天気"},
{vi:"núi",jp:"山",pos:"名詞",hanviet:"",ex_vi:"Núi Phú Sĩ.",ex_jp:"富士山。",note:"",cat:"自然・天気"},
{vi:"sông",jp:"川",pos:"名詞",hanviet:"",ex_vi:"Sông Hồng.",ex_jp:"紅河。",note:"",cat:"自然・天気"},
{vi:"hồ",jp:"湖",pos:"名詞",hanviet:"湖",ex_vi:"Hồ Tây.",ex_jp:"西湖。",note:"",cat:"自然・天気"},
{vi:"biển",jp:"海",pos:"名詞",hanviet:"",ex_vi:"Đi biển.",ex_jp:"海に行く。",note:"",cat:"自然・天気"},
{vi:"rừng",jp:"森林",pos:"名詞",hanviet:"",ex_vi:"Rừng nhiệt đới.",ex_jp:"熱帯雨林。",note:"",cat:"自然・天気"},
{vi:"đảo",jp:"島",pos:"名詞",hanviet:"島",ex_vi:"Đảo Phú Quốc.",ex_jp:"フーコック島。",note:"",cat:"自然・天気"},
{vi:"bãi biển",jp:"砂浜",pos:"名詞",hanviet:"",ex_vi:"Bãi biển đẹp.",ex_jp:"砂浜が綺麗。",note:"",cat:"自然・天気"},
{vi:"môi trường",jp:"環境",pos:"名詞",hanviet:"環境",ex_vi:"Bảo vệ môi trường.",ex_jp:"環境を守る。",note:"",cat:"自然・天気"},
{vi:"ô nhiễm",jp:"汚染",pos:"名詞",hanviet:"汚染",ex_vi:"Ô nhiễm không khí.",ex_jp:"大気汚染。",note:"",cat:"自然・天気"},
{vi:"không khí",jp:"空気",pos:"名詞",hanviet:"空気",ex_vi:"Không khí trong lành.",ex_jp:"空気が清新。",note:"",cat:"自然・天気"},
{vi:"mùa",jp:"季節",pos:"名詞",hanviet:"",ex_vi:"4 mùa.",ex_jp:"四季。",note:"",cat:"自然・天気"},
{vi:"mùa xuân",jp:"春",pos:"名詞",hanviet:"-春",ex_vi:"Mùa xuân ấm.",ex_jp:"春は暖かい。",note:"",cat:"自然・天気"},
{vi:"mùa hè",jp:"夏",pos:"名詞",hanviet:"",ex_vi:"Mùa hè nóng.",ex_jp:"夏は暑い。",note:"",cat:"自然・天気"},
{vi:"mùa thu",jp:"秋",pos:"名詞",hanviet:"-秋",ex_vi:"Mùa thu mát.",ex_jp:"秋は涼しい。",note:"⚠️thu=秋",cat:"自然・天気"},
{vi:"mùa đông",jp:"冬",pos:"名詞",hanviet:"-冬",ex_vi:"Mùa đông lạnh.",ex_jp:"冬は寒い。",note:"",cat:"自然・天気"},
{vi:"nóng",jp:"暑い・熱い",pos:"形容詞",hanviet:"",ex_vi:"Trời nóng.",ex_jp:"暑い。",note:"",cat:"自然・天気"},
{vi:"lạnh",jp:"寒い・冷たい",pos:"形容詞",hanviet:"",ex_vi:"Nước lạnh.",ex_jp:"水が冷たい。",note:"⚠️lành=健康",cat:"自然・天気"},
{vi:"ấm",jp:"暖かい",pos:"形容詞",hanviet:"",ex_vi:"Trời ấm.",ex_jp:"暖かい天気。",note:"",cat:"自然・天気"},
{vi:"mát",jp:"涼しい",pos:"形容詞",hanviet:"",ex_vi:"Gió mát.",ex_jp:"涼しい風。",note:"⚠️mất=無くす",cat:"自然・天気"},
{vi:"nắng",jp:"晴れ・日差し",pos:"名詞",hanviet:"",ex_vi:"Trời nắng.",ex_jp:"晴れている。",note:"⚠️nặng=重い",cat:"自然・天気"},
{vi:"khô",jp:"乾燥した",pos:"形容詞",hanviet:"",ex_vi:"Mùa khô.",ex_jp:"乾季。",note:"",cat:"自然・天気"},
{vi:"ẩm",jp:"湿った",pos:"形容詞",hanviet:"",ex_vi:"Trời ẩm.",ex_jp:"湿気がある。",note:"",cat:"自然・天気"},
{vi:"động đất",jp:"地震",pos:"名詞",hanviet:"動土",ex_vi:"Động đất ở Nhật.",ex_jp:"日本で地震。",note:"",cat:"自然・天気"},
{vi:"lũ lụt",jp:"洪水",pos:"名詞",hanviet:"",ex_vi:"Lũ lụt miền Trung.",ex_jp:"中部で洪水。",note:"",cat:"自然・天気"},

// === 12. 動物・植物 (25) ===
{vi:"chó",jp:"犬",pos:"名詞",hanviet:"",ex_vi:"Con chó nhỏ.",ex_jp:"小さな犬。",note:"",cat:"動物・植物"},
{vi:"mèo",jp:"猫",pos:"名詞",hanviet:"",ex_vi:"Con mèo trắng.",ex_jp:"白い猫。",note:"",cat:"動物・植物"},
{vi:"con",jp:"動物の類別詞",pos:"類別詞",hanviet:"",ex_vi:"Một con cá.",ex_jp:"魚1匹。",note:"類別詞",cat:"動物・植物"},
{vi:"chim",jp:"鳥",pos:"名詞",hanviet:"",ex_vi:"Chim hót.",ex_jp:"鳥がさえずる。",note:"",cat:"動物・植物"},
{vi:"gà",jp:"鶏",pos:"名詞",hanviet:"",ex_vi:"Gà gáy.",ex_jp:"鶏が鳴く。",note:"",cat:"動物・植物"},
{vi:"vịt",jp:"アヒル",pos:"名詞",hanviet:"",ex_vi:"Thịt vịt quay.",ex_jp:"焼きアヒル。",note:"",cat:"動物・植物"},
{vi:"bò",jp:"牛",pos:"名詞",hanviet:"",ex_vi:"Con bò đen.",ex_jp:"黒い牛。",note:"",cat:"動物・植物"},
{vi:"lợn",jp:"豚",pos:"名詞",hanviet:"",ex_vi:"Con lợn.",ex_jp:"豚。",note:"南部はheo",cat:"動物・植物"},
{vi:"ngựa",jp:"馬",pos:"名詞",hanviet:"",ex_vi:"Cưỡi ngựa.",ex_jp:"馬に乗る。",note:"",cat:"動物・植物"},
{vi:"voi",jp:"象",pos:"名詞",hanviet:"",ex_vi:"Con voi to.",ex_jp:"大きな象。",note:"",cat:"動物・植物"},
{vi:"hổ",jp:"虎",pos:"名詞",hanviet:"虎",ex_vi:"Con hổ Việt Nam.",ex_jp:"ベトナムの虎。",note:"",cat:"動物・植物"},
{vi:"khỉ",jp:"猿",pos:"名詞",hanviet:"",ex_vi:"Con khỉ thông minh.",ex_jp:"利口な猿。",note:"",cat:"動物・植物"},
{vi:"rắn",jp:"蛇",pos:"名詞",hanviet:"",ex_vi:"Rắn độc.",ex_jp:"毒蛇。",note:"",cat:"動物・植物"},
{vi:"cây",jp:"木",pos:"名詞",hanviet:"",ex_vi:"Cây xanh.",ex_jp:"木は緑。",note:"",cat:"動物・植物"},
{vi:"hoa",jp:"花",pos:"名詞",hanviet:"花",ex_vi:"Hoa đẹp.",ex_jp:"花が綺麗。",note:"",cat:"動物・植物"},
{vi:"lá",jp:"葉",pos:"名詞",hanviet:"",ex_vi:"Lá vàng mùa thu.",ex_jp:"秋の黄葉。",note:"",cat:"動物・植物"},
{vi:"cỏ",jp:"草",pos:"名詞",hanviet:"",ex_vi:"Cỏ xanh.",ex_jp:"緑の草。",note:"",cat:"動物・植物"},
{vi:"hoa hồng",jp:"バラ",pos:"名詞",hanviet:"花紅",ex_vi:"Bó hoa hồng đỏ.",ex_jp:"赤いバラの花束。",note:"",cat:"動物・植物"},
{vi:"hoa mai",jp:"梅の花",pos:"名詞",hanviet:"花梅",ex_vi:"Hoa mai vàng.",ex_jp:"黄色い梅の花。",note:"",cat:"動物・植物"},
{vi:"trồng",jp:"植える",pos:"動詞-動作",hanviet:"",ex_vi:"Trồng cây.",ex_jp:"木を植える。",note:"⚠️trông=見る",cat:"動物・植物"},
{vi:"rau muống",jp:"空芯菜",pos:"名詞",hanviet:"",ex_vi:"Rau muống xào tỏi.",ex_jp:"空芯菜のニンニク炒め。",note:"",cat:"動物・植物"},
{vi:"hoa quả",jp:"果物",pos:"名詞",hanviet:"花果",ex_vi:"Hoa quả nhiệt đới.",ex_jp:"熱帯の果物。",note:"",cat:"動物・植物"},
{vi:"cá vàng",jp:"金魚",pos:"名詞",hanviet:"-黄",ex_vi:"Cá vàng nhỏ.",ex_jp:"小さな金魚。",note:"",cat:"動物・植物"},
{vi:"con muỗi",jp:"蚊",pos:"名詞",hanviet:"",ex_vi:"Muỗi đốt.",ex_jp:"蚊に刺される。",note:"",cat:"動物・植物"},
{vi:"con kiến",jp:"アリ",pos:"名詞",hanviet:"",ex_vi:"Đàn kiến.",ex_jp:"アリの群れ。",note:"",cat:"動物・植物"},

// === 13. 色・形 (20) ===
{vi:"màu",jp:"色",pos:"名詞",hanviet:"",ex_vi:"Màu sắc đẹp.",ex_jp:"色が綺麗。",note:"",cat:"色・形"},
{vi:"đỏ",jp:"赤",pos:"形容詞",hanviet:"",ex_vi:"Áo đỏ.",ex_jp:"赤い服。",note:"",cat:"色・形"},
{vi:"xanh",jp:"青・緑",pos:"形容詞",hanviet:"",ex_vi:"Trời xanh.",ex_jp:"青空。",note:"",cat:"色・形"},
{vi:"vàng",jp:"黄色",pos:"形容詞",hanviet:"",ex_vi:"Hoa vàng.",ex_jp:"黄色い花。",note:"",cat:"色・形"},
{vi:"trắng",jp:"白",pos:"形容詞",hanviet:"",ex_vi:"Áo trắng.",ex_jp:"白いシャツ。",note:"",cat:"色・形"},
{vi:"đen",jp:"黒",pos:"形容詞",hanviet:"",ex_vi:"Mắt đen.",ex_jp:"黒い瞳。",note:"",cat:"色・形"},
{vi:"hồng",jp:"ピンク",pos:"形容詞",hanviet:"紅",ex_vi:"Hoa hồng màu hồng.",ex_jp:"ピンクのバラ。",note:"",cat:"色・形"},
{vi:"tím",jp:"紫",pos:"形容詞",hanviet:"",ex_vi:"Áo tím.",ex_jp:"紫の服。",note:"",cat:"色・形"},
{vi:"nâu",jp:"茶色",pos:"形容詞",hanviet:"",ex_vi:"Tóc nâu.",ex_jp:"茶髪。",note:"",cat:"色・形"},
{vi:"xám",jp:"灰色",pos:"形容詞",hanviet:"",ex_vi:"Mây xám.",ex_jp:"灰色の雲。",note:"",cat:"色・形"},
{vi:"cam",jp:"オレンジ色",pos:"形容詞",hanviet:"",ex_vi:"Áo màu cam.",ex_jp:"オレンジの服。",note:"果物のオレンジも同じ語",cat:"色・形"},
{vi:"hình",jp:"形",pos:"名詞",hanviet:"形",ex_vi:"Hình tròn.",ex_jp:"丸い形。",note:"",cat:"色・形"},
{vi:"tròn",jp:"丸い",pos:"形容詞",hanviet:"",ex_vi:"Mặt tròn.",ex_jp:"丸い顔。",note:"",cat:"色・形"},
{vi:"vuông",jp:"四角い",pos:"形容詞",hanviet:"",ex_vi:"Bàn vuông.",ex_jp:"四角い机。",note:"",cat:"色・形"},
{vi:"dài",jp:"長い",pos:"形容詞",hanviet:"",ex_vi:"Tóc dài.",ex_jp:"髪が長い。",note:"",cat:"色・形"},
{vi:"ngắn",jp:"短い",pos:"形容詞",hanviet:"",ex_vi:"Quần ngắn.",ex_jp:"短いズボン。",note:"",cat:"色・形"},
{vi:"to",jp:"大きい",pos:"形容詞",hanviet:"",ex_vi:"Nhà to.",ex_jp:"大きな家。",note:"",cat:"色・形"},
{vi:"nhỏ",jp:"小さい",pos:"形容詞",hanviet:"",ex_vi:"Em bé nhỏ.",ex_jp:"小さな赤ちゃん。",note:"⚠️nhớ=覚える",cat:"色・形"},
{vi:"dày",jp:"厚い",pos:"形容詞",hanviet:"",ex_vi:"Sách dày.",ex_jp:"厚い本。",note:"",cat:"色・形"},
{vi:"mỏng",jp:"薄い",pos:"形容詞",hanviet:"",ex_vi:"Áo mỏng.",ex_jp:"薄い服。",note:"",cat:"色・形"},

// === 14. 時間表現 (30) ===
{vi:"thời gian",jp:"時間",pos:"名詞",hanviet:"時間",ex_vi:"Có thời gian không?",ex_jp:"時間ある?",note:"",cat:"時間表現"},
{vi:"giờ",jp:"時刻・時",pos:"名詞",hanviet:"",ex_vi:"Mấy giờ?",ex_jp:"何時?",note:"",cat:"時間表現"},
{vi:"phút",jp:"分",pos:"名詞",hanviet:"",ex_vi:"5 phút.",ex_jp:"5分。",note:"",cat:"時間表現"},
{vi:"giây",jp:"秒",pos:"名詞",hanviet:"",ex_vi:"30 giây.",ex_jp:"30秒。",note:"",cat:"時間表現"},
{vi:"ngày",jp:"日",pos:"名詞",hanviet:"",ex_vi:"Hôm nay là ngày 5.",ex_jp:"今日は5日。",note:"",cat:"時間表現"},
{vi:"tuần",jp:"週",pos:"名詞",hanviet:"",ex_vi:"Tuần này.",ex_jp:"今週。",note:"",cat:"時間表現"},
{vi:"tháng",jp:"月",pos:"名詞",hanviet:"",ex_vi:"Tháng 5.",ex_jp:"5月。",note:"",cat:"時間表現"},
{vi:"năm",jp:"年",pos:"名詞",hanviet:"年",ex_vi:"Năm 2026.",ex_jp:"2026年。",note:"年と数字の5は同じ綴",cat:"時間表現"},
{vi:"hôm nay",jp:"今日",pos:"名詞",hanviet:"",ex_vi:"Hôm nay đẹp.",ex_jp:"今日は良い日。",note:"",cat:"時間表現"},
{vi:"hôm qua",jp:"昨日",pos:"名詞",hanviet:"",ex_vi:"Hôm qua mưa.",ex_jp:"昨日は雨。",note:"",cat:"時間表現"},
{vi:"ngày mai",jp:"明日",pos:"名詞",hanviet:"",ex_vi:"Ngày mai họp.",ex_jp:"明日会議。",note:"",cat:"時間表現"},
{vi:"sáng",jp:"朝",pos:"名詞",hanviet:"",ex_vi:"Buổi sáng.",ex_jp:"朝。",note:"",cat:"時間表現"},
{vi:"trưa",jp:"昼",pos:"名詞",hanviet:"",ex_vi:"Ăn trưa.",ex_jp:"昼食。",note:"",cat:"時間表現"},
{vi:"chiều",jp:"午後",pos:"名詞",hanviet:"",ex_vi:"Chiều nay.",ex_jp:"今日の午後。",note:"",cat:"時間表現"},
{vi:"tối",jp:"夜",pos:"名詞",hanviet:"",ex_vi:"Tối nay.",ex_jp:"今夜。",note:"",cat:"時間表現"},
{vi:"đêm",jp:"夜中",pos:"名詞",hanviet:"",ex_vi:"Đêm khuya.",ex_jp:"深夜。",note:"",cat:"時間表現"},
{vi:"hiện tại",jp:"現在",pos:"名詞",hanviet:"現在",ex_vi:"Hiện tại tôi bận.",ex_jp:"今は忙しい。",note:"",cat:"時間表現"},
{vi:"quá khứ",jp:"過去",pos:"名詞",hanviet:"過去",ex_vi:"Quên đi quá khứ.",ex_jp:"過去を忘れる。",note:"",cat:"時間表現"},
{vi:"tương lai",jp:"未来",pos:"名詞",hanviet:"将来",ex_vi:"Tương lai sáng.",ex_jp:"明るい未来。",note:"",cat:"時間表現"},
{vi:"đúng giờ",jp:"時間通り",pos:"形容詞",hanviet:"",ex_vi:"Đến đúng giờ.",ex_jp:"時間通りに着く。",note:"",cat:"時間表現"},
{vi:"sớm",jp:"早い(時刻)",pos:"形容詞",hanviet:"",ex_vi:"Dậy sớm.",ex_jp:"早く起きる。",note:"",cat:"時間表現"},
{vi:"muộn",jp:"遅い・遅刻",pos:"形容詞",hanviet:"",ex_vi:"Đi làm muộn.",ex_jp:"遅刻する。",note:"⚠️muốn=欲しい",cat:"時間表現"},
{vi:"ngay",jp:"すぐに",pos:"副詞",hanviet:"",ex_vi:"Đến ngay.",ex_jp:"すぐ来る。",note:"",cat:"時間表現"},
{vi:"đột nhiên",jp:"突然",pos:"副詞",hanviet:"突然",ex_vi:"Đột nhiên mưa.",ex_jp:"突然雨が降る。",note:"",cat:"時間表現"},
{vi:"thường xuyên",jp:"頻繁に",pos:"副詞",hanviet:"常宣",ex_vi:"Thường xuyên đi.",ex_jp:"頻繁に行く。",note:"",cat:"時間表現"},
{vi:"đôi khi",jp:"時々",pos:"副詞",hanviet:"",ex_vi:"Đôi khi nhớ nhà.",ex_jp:"時々ホームシック。",note:"",cat:"時間表現"},
{vi:"luôn luôn",jp:"いつも",pos:"副詞",hanviet:"",ex_vi:"Luôn luôn vui.",ex_jp:"いつも楽しい。",note:"",cat:"時間表現"},
{vi:"không bao giờ",jp:"決して〜ない",pos:"副詞",hanviet:"",ex_vi:"Không bao giờ về.",ex_jp:"決して帰らない。",note:"",cat:"時間表現"},
{vi:"trước",jp:"前",pos:"前置詞",hanviet:"",ex_vi:"Trước khi đi.",ex_jp:"行く前に。",note:"",cat:"時間表現"},
{vi:"sau",jp:"後",pos:"前置詞",hanviet:"",ex_vi:"Sau khi ăn.",ex_jp:"食べた後。",note:"",cat:"時間表現"},

// === 15. 感情・性格 (40) ===
{vi:"vui vẻ",jp:"嬉しい・楽しい",pos:"形容詞",hanviet:"",ex_vi:"Tâm trạng vui vẻ.",ex_jp:"気分が良い。",note:"",cat:"感情・性格"},
{vi:"hạnh phúc",jp:"幸せ",pos:"形容詞",hanviet:"幸福",ex_vi:"Gia đình hạnh phúc.",ex_jp:"幸せな家庭。",note:"",cat:"感情・性格"},
{vi:"buồn",jp:"悲しい",pos:"形容詞",hanviet:"",ex_vi:"Tôi buồn.",ex_jp:"私は悲しい。",note:"",cat:"感情・性格"},
{vi:"tức giận",jp:"怒る",pos:"動詞-状態",hanviet:"",ex_vi:"Bố tức giận.",ex_jp:"父が怒っている。",note:"",cat:"感情・性格"},
{vi:"sợ",jp:"怖がる",pos:"動詞-状態",hanviet:"",ex_vi:"Sợ chó.",ex_jp:"犬が怖い。",note:"",cat:"感情・性格"},
{vi:"lo lắng",jp:"心配する",pos:"動詞-状態",hanviet:"",ex_vi:"Lo lắng cho con.",ex_jp:"子供を心配する。",note:"",cat:"感情・性格"},
{vi:"ngạc nhiên",jp:"驚く",pos:"動詞-状態",hanviet:"愕然",ex_vi:"Tôi rất ngạc nhiên.",ex_jp:"とても驚いた。",note:"",cat:"感情・性格"},
{vi:"xấu hổ",jp:"恥ずかしい",pos:"形容詞",hanviet:"",ex_vi:"Cảm thấy xấu hổ.",ex_jp:"恥ずかしい。",note:"",cat:"感情・性格"},
{vi:"cô đơn",jp:"孤独",pos:"形容詞",hanviet:"孤単",ex_vi:"Cảm thấy cô đơn.",ex_jp:"孤独を感じる。",note:"",cat:"感情・性格"},
{vi:"thất vọng",jp:"失望する",pos:"動詞-状態",hanviet:"失望",ex_vi:"Thất vọng về kết quả.",ex_jp:"結果に失望。",note:"",cat:"感情・性格"},
{vi:"hài lòng",jp:"満足する",pos:"動詞-状態",hanviet:"懐量",ex_vi:"Hài lòng với công việc.",ex_jp:"仕事に満足。",note:"",cat:"感情・性格"},
{vi:"thoải mái",jp:"くつろぐ・快適",pos:"形容詞",hanviet:"",ex_vi:"Cảm thấy thoải mái.",ex_jp:"快適だ。",note:"",cat:"感情・性格"},
{vi:"căng thẳng",jp:"緊張・ストレス",pos:"形容詞",hanviet:"",ex_vi:"Căng thẳng trước thi.",ex_jp:"試験前緊張。",note:"",cat:"感情・性格"},
{vi:"hồi hộp",jp:"ドキドキする",pos:"動詞-状態",hanviet:"",ex_vi:"Hồi hộp đợi kết quả.",ex_jp:"結果を待ちドキドキ。",note:"",cat:"感情・性格"},
{vi:"yên tâm",jp:"安心する",pos:"動詞-状態",hanviet:"安心",ex_vi:"Tôi yên tâm rồi.",ex_jp:"安心した。",note:"",cat:"感情・性格"},
{vi:"thích",jp:"好き",pos:"動詞-状態",hanviet:"",ex_vi:"Tôi thích phở.",ex_jp:"フォーが好き。",note:"",cat:"感情・性格"},
{vi:"tốt bụng",jp:"親切",pos:"形容詞",hanviet:"",ex_vi:"Người tốt bụng.",ex_jp:"親切な人。",note:"",cat:"感情・性格"},
{vi:"hiền",jp:"優しい",pos:"形容詞",hanviet:"",ex_vi:"Mẹ hiền.",ex_jp:"優しい母。",note:"",cat:"感情・性格"},
{vi:"thông minh",jp:"賢い",pos:"形容詞",hanviet:"聡明",ex_vi:"Trẻ thông minh.",ex_jp:"賢い子供。",note:"",cat:"感情・性格"},
{vi:"trung thực",jp:"誠実",pos:"形容詞",hanviet:"忠実",ex_vi:"Người trung thực.",ex_jp:"誠実な人。",note:"",cat:"感情・性格"},
{vi:"vui tính",jp:"明るい性格",pos:"形容詞",hanviet:"",ex_vi:"Anh ấy vui tính.",ex_jp:"彼は明るい。",note:"",cat:"感情・性格"},
{vi:"nghiêm túc",jp:"真面目",pos:"形容詞",hanviet:"厳粛",ex_vi:"Sinh viên nghiêm túc.",ex_jp:"真面目な学生。",note:"",cat:"感情・性格"},
{vi:"lười biếng",jp:"怠惰",pos:"形容詞",hanviet:"",ex_vi:"Tránh lười biếng.",ex_jp:"怠惰を避ける。",note:"",cat:"感情・性格"},
{vi:"ích kỷ",jp:"利己的",pos:"形容詞",hanviet:"",ex_vi:"Người ích kỷ.",ex_jp:"利己的な人。",note:"",cat:"感情・性格"},
{vi:"keo kiệt",jp:"ケチ",pos:"形容詞",hanviet:"",ex_vi:"Keo kiệt với bạn.",ex_jp:"友達にケチ。",note:"",cat:"感情・性格"},
{vi:"nhút nhát",jp:"内気",pos:"形容詞",hanviet:"",ex_vi:"Cô ấy nhút nhát.",ex_jp:"彼女は内気。",note:"",cat:"感情・性格"},
{vi:"tự tin",jp:"自信がある",pos:"形容詞",hanviet:"自信",ex_vi:"Anh ấy tự tin.",ex_jp:"彼は自信がある。",note:"",cat:"感情・性格"},
{vi:"khiêm tốn",jp:"謙虚",pos:"形容詞",hanviet:"謙遜",ex_vi:"Người khiêm tốn.",ex_jp:"謙虚な人。",note:"",cat:"感情・性格"},
{vi:"kiên nhẫn",jp:"忍耐強い",pos:"形容詞",hanviet:"堅忍",ex_vi:"Cần kiên nhẫn.",ex_jp:"忍耐が必要。",note:"",cat:"感情・性格"},
{vi:"hy vọng",jp:"希望",pos:"動詞-状態",hanviet:"希望",ex_vi:"Hy vọng đỗ đại học.",ex_jp:"大学合格を希望。",note:"",cat:"感情・性格"},
{vi:"yêu thương",jp:"愛する",pos:"動詞-状態",hanviet:"",ex_vi:"Yêu thương gia đình.",ex_jp:"家族を愛する。",note:"",cat:"感情・性格"},
{vi:"nhớ",jp:"覚える・恋しがる",pos:"動詞-状態",hanviet:"",ex_vi:"Nhớ nhà.",ex_jp:"ホームシック。",note:"⚠️nhỏ=小さい",cat:"感情・性格"},
{vi:"quên",jp:"忘れる",pos:"動詞-動作",hanviet:"",ex_vi:"Quên mất.",ex_jp:"忘れた。",note:"",cat:"感情・性格"},
{vi:"hối hận",jp:"後悔する",pos:"動詞-状態",hanviet:"悔恨",ex_vi:"Hối hận về quá khứ.",ex_jp:"過去を後悔。",note:"",cat:"感情・性格"},
{vi:"tin tưởng",jp:"信頼する",pos:"動詞-状態",hanviet:"信想",ex_vi:"Tin tưởng anh.",ex_jp:"あなたを信頼。",note:"",cat:"感情・性格"},
{vi:"nghi ngờ",jp:"疑う",pos:"動詞-状態",hanviet:"疑偶",ex_vi:"Nghi ngờ lời nói.",ex_jp:"言葉を疑う。",note:"",cat:"感情・性格"},
{vi:"khó chịu",jp:"不快",pos:"形容詞",hanviet:"",ex_vi:"Tôi cảm thấy khó chịu.",ex_jp:"不快だ。",note:"",cat:"感情・性格"},
{vi:"chán",jp:"うんざり",pos:"形容詞",hanviet:"",ex_vi:"Chán việc này.",ex_jp:"この仕事に飽きた。",note:"",cat:"感情・性格"},
{vi:"yêu",jp:"愛する",pos:"動詞-状態",hanviet:"",ex_vi:"Tôi yêu em.",ex_jp:"あなたを愛している。",note:"",cat:"感情・性格"},
{vi:"đáng yêu",jp:"可愛い",pos:"形容詞",hanviet:"",ex_vi:"Em bé đáng yêu.",ex_jp:"可愛い赤ちゃん。",note:"",cat:"感情・性格"},

// === 16. 基本動作の動詞 (40) ===
{vi:"đứng",jp:"立つ",pos:"動詞-動作",hanviet:"",ex_vi:"Đứng lên.",ex_jp:"立ち上がる。",note:"⚠️đừng=するな",cat:"基本動作"},
{vi:"ngồi",jp:"座る",pos:"動詞-動作",hanviet:"",ex_vi:"Ngồi xuống.",ex_jp:"座る。",note:"",cat:"基本動作"},
{vi:"nằm",jp:"横になる",pos:"動詞-動作",hanviet:"",ex_vi:"Nằm trên giường.",ex_jp:"ベッドに横になる。",note:"⚠️nắm=握る",cat:"基本動作"},
{vi:"đi",jp:"行く・歩く",pos:"動詞-動作",hanviet:"",ex_vi:"Đi đâu?",ex_jp:"どこ行く?",note:"",cat:"基本動作"},
{vi:"chạy",jp:"走る",pos:"動詞-動作",hanviet:"",ex_vi:"Chạy nhanh.",ex_jp:"速く走る。",note:"",cat:"基本動作"},
{vi:"nhảy",jp:"跳ぶ・踊る",pos:"動詞-動作",hanviet:"",ex_vi:"Nhảy lên.",ex_jp:"跳び上がる。",note:"",cat:"基本動作"},
{vi:"nhìn",jp:"見る",pos:"動詞-動作",hanviet:"",ex_vi:"Nhìn lên.",ex_jp:"見上げる。",note:"⚠️nghìn=1000",cat:"基本動作"},
{vi:"xem",jp:"見る(鑑賞)",pos:"動詞-動作",hanviet:"",ex_vi:"Xem phim.",ex_jp:"映画を見る。",note:"",cat:"基本動作"},
{vi:"nghe",jp:"聞く",pos:"動詞-動作",hanviet:"",ex_vi:"Nghe nhạc.",ex_jp:"音楽を聞く。",note:"",cat:"基本動作"},
{vi:"nói",jp:"話す",pos:"動詞-動作",hanviet:"",ex_vi:"Nói tiếng Việt.",ex_jp:"ベトナム語を話す。",note:"",cat:"基本動作"},
{vi:"đọc",jp:"読む",pos:"動詞-動作",hanviet:"",ex_vi:"Đọc báo.",ex_jp:"新聞を読む。",note:"",cat:"基本動作"},
{vi:"viết",jp:"書く",pos:"動詞-動作",hanviet:"",ex_vi:"Viết thư.",ex_jp:"手紙を書く。",note:"",cat:"基本動作"},
{vi:"hỏi",jp:"質問する",pos:"動詞-動作",hanviet:"",ex_vi:"Hỏi giáo viên.",ex_jp:"先生に質問する。",note:"",cat:"基本動作"},
{vi:"trả lời",jp:"答える",pos:"動詞-動作",hanviet:"",ex_vi:"Trả lời câu hỏi.",ex_jp:"質問に答える。",note:"",cat:"基本動作"},
{vi:"gọi",jp:"呼ぶ",pos:"動詞-動作",hanviet:"",ex_vi:"Gọi điện thoại.",ex_jp:"電話する。",note:"⚠️gợi=提案",cat:"基本動作"},
{vi:"đợi",jp:"待つ",pos:"動詞-動作",hanviet:"",ex_vi:"Đợi tôi.",ex_jp:"待ってください。",note:"",cat:"基本動作"},
{vi:"tìm",jp:"探す",pos:"動詞-動作",hanviet:"",ex_vi:"Tìm chìa khóa.",ex_jp:"鍵を探す。",note:"",cat:"基本動作"},
{vi:"tìm thấy",jp:"見つける",pos:"動詞-動作",hanviet:"",ex_vi:"Tìm thấy ví.",ex_jp:"財布を見つけた。",note:"",cat:"基本動作"},
{vi:"mở",jp:"開ける",pos:"動詞-動作",hanviet:"",ex_vi:"Mở cửa.",ex_jp:"ドアを開ける。",note:"",cat:"基本動作"},
{vi:"đóng",jp:"閉める",pos:"動詞-動作",hanviet:"",ex_vi:"Đóng cửa sổ.",ex_jp:"窓を閉める。",note:"",cat:"基本動作"},
{vi:"bật",jp:"点ける",pos:"動詞-動作",hanviet:"",ex_vi:"Bật đèn.",ex_jp:"電気をつける。",note:"",cat:"基本動作"},
{vi:"tắt",jp:"消す",pos:"動詞-動作",hanviet:"",ex_vi:"Tắt máy lạnh.",ex_jp:"エアコンを消す。",note:"",cat:"基本動作"},
{vi:"cầm",jp:"手に持つ",pos:"動詞-動作",hanviet:"",ex_vi:"Cầm bút.",ex_jp:"ペンを持つ。",note:"⚠️cấm=禁止",cat:"基本動作"},
{vi:"đưa",jp:"渡す",pos:"動詞-動作",hanviet:"",ex_vi:"Đưa tay.",ex_jp:"手を出す。",note:"",cat:"基本動作"},
{vi:"nhận",jp:"受け取る",pos:"動詞-動作",hanviet:"",ex_vi:"Nhận quà.",ex_jp:"プレゼントを受け取る。",note:"⚠️nhắn=メッセージ",cat:"基本動作"},
{vi:"cho",jp:"あげる・〜させる",pos:"動詞-動作",hanviet:"",ex_vi:"Cho tôi xem.",ex_jp:"見せてください。",note:"",cat:"基本動作"},
{vi:"lấy",jp:"取る",pos:"動詞-動作",hanviet:"",ex_vi:"Lấy sách.",ex_jp:"本を取る。",note:"",cat:"基本動作"},
{vi:"gửi",jp:"送る",pos:"動詞-動作",hanviet:"",ex_vi:"Gửi thư.",ex_jp:"手紙を送る。",note:"",cat:"基本動作"},
{vi:"đến",jp:"来る・到着",pos:"動詞-動作",hanviet:"",ex_vi:"Đến lúc 7h.",ex_jp:"7時に着く。",note:"",cat:"基本動作"},
{vi:"đi ra",jp:"出る",pos:"動詞-動作",hanviet:"",ex_vi:"Đi ra ngoài.",ex_jp:"外に出る。",note:"",cat:"基本動作"},
{vi:"đi vào",jp:"入る",pos:"動詞-動作",hanviet:"",ex_vi:"Đi vào phòng.",ex_jp:"部屋に入る。",note:"",cat:"基本動作"},
{vi:"lên",jp:"上がる",pos:"動詞-動作",hanviet:"",ex_vi:"Lên cầu thang.",ex_jp:"階段を上がる。",note:"",cat:"基本動作"},
{vi:"xuống",jp:"下りる",pos:"動詞-動作",hanviet:"",ex_vi:"Xuống tầng 1.",ex_jp:"1階に降りる。",note:"",cat:"基本動作"},
{vi:"bắt đầu",jp:"始める",pos:"動詞-動作",hanviet:"",ex_vi:"Bắt đầu học.",ex_jp:"勉強を始める。",note:"",cat:"基本動作"},
{vi:"kết thúc",jp:"終わる",pos:"動詞-動作",hanviet:"結束",ex_vi:"Kết thúc lúc 5h.",ex_jp:"5時に終わる。",note:"",cat:"基本動作"},
{vi:"tiếp tục",jp:"続ける",pos:"動詞-動作",hanviet:"接続",ex_vi:"Tiếp tục học.",ex_jp:"学習を続ける。",note:"",cat:"基本動作"},
{vi:"dừng lại",jp:"止まる",pos:"動詞-動作",hanviet:"",ex_vi:"Dừng lại đây.",ex_jp:"ここで止まる。",note:"",cat:"基本動作"},
{vi:"quên",jp:"忘れる",pos:"動詞-動作",hanviet:"",ex_vi:"Quên ví.",ex_jp:"財布を忘れる。",note:"",cat:"基本動作"},
{vi:"giúp",jp:"助ける",pos:"動詞-動作",hanviet:"",ex_vi:"Giúp tôi.",ex_jp:"私を助けて。",note:"",cat:"基本動作"},
{vi:"sử dụng",jp:"使用する",pos:"動詞-動作",hanviet:"使用",ex_vi:"Sử dụng máy tính.",ex_jp:"パソコンを使う。",note:"",cat:"基本動作"},

// === 17. 形容詞 (40) ===
{vi:"tốt",jp:"良い",pos:"形容詞",hanviet:"",ex_vi:"Anh ấy tốt.",ex_jp:"彼は良い人。",note:"",cat:"形容詞"},
{vi:"xấu",jp:"悪い・ブサイク",pos:"形容詞",hanviet:"",ex_vi:"Thời tiết xấu.",ex_jp:"天気が悪い。",note:"",cat:"形容詞"},
{vi:"đẹp",jp:"美しい",pos:"形容詞",hanviet:"",ex_vi:"Cô ấy đẹp.",ex_jp:"彼女は美しい。",note:"",cat:"形容詞"},
{vi:"mới",jp:"新しい・たった今",pos:"形容詞",hanviet:"",ex_vi:"Áo mới.",ex_jp:"新しい服。",note:"⚠️mời=招く",cat:"形容詞"},
{vi:"cũ",jp:"古い",pos:"形容詞",hanviet:"",ex_vi:"Sách cũ.",ex_jp:"古い本。",note:"",cat:"形容詞"},
{vi:"trẻ",jp:"若い",pos:"形容詞",hanviet:"",ex_vi:"Sinh viên trẻ.",ex_jp:"若い学生。",note:"",cat:"形容詞"},
{vi:"già",jp:"年老いた",pos:"形容詞",hanviet:"",ex_vi:"Người già.",ex_jp:"年配の人。",note:"⚠️giá=値段",cat:"形容詞"},
{vi:"nhanh",jp:"速い",pos:"形容詞",hanviet:"",ex_vi:"Đi nhanh.",ex_jp:"速く行く。",note:"",cat:"形容詞"},
{vi:"chậm",jp:"遅い",pos:"形容詞",hanviet:"",ex_vi:"Đi chậm.",ex_jp:"ゆっくり行く。",note:"",cat:"形容詞"},
{vi:"khó",jp:"難しい",pos:"形容詞",hanviet:"",ex_vi:"Tiếng Việt khó.",ex_jp:"ベトナム語は難しい。",note:"",cat:"形容詞"},
{vi:"dễ",jp:"簡単",pos:"形容詞",hanviet:"",ex_vi:"Bài tập dễ.",ex_jp:"宿題は簡単。",note:"",cat:"形容詞"},
{vi:"đúng",jp:"正しい",pos:"形容詞",hanviet:"",ex_vi:"Câu trả lời đúng.",ex_jp:"正しい答え。",note:"⚠️đứng=立つ",cat:"形容詞"},
{vi:"sai",jp:"間違っている",pos:"形容詞",hanviet:"",ex_vi:"Sai rồi.",ex_jp:"間違えた。",note:"",cat:"形容詞"},
{vi:"quan trọng",jp:"重要",pos:"形容詞",hanviet:"関重",ex_vi:"Việc quan trọng.",ex_jp:"重要な仕事。",note:"",cat:"形容詞"},
{vi:"đặc biệt",jp:"特別",pos:"形容詞",hanviet:"特別",ex_vi:"Ngày đặc biệt.",ex_jp:"特別な日。",note:"",cat:"形容詞"},
{vi:"bình thường",jp:"普通",pos:"形容詞",hanviet:"平常",ex_vi:"Bình thường.",ex_jp:"普通です。",note:"",cat:"形容詞"},
{vi:"đầy",jp:"満ちている",pos:"形容詞",hanviet:"",ex_vi:"Cốc đầy nước.",ex_jp:"コップに水が満ちている。",note:"",cat:"形容詞"},
{vi:"trống",jp:"空(から)",pos:"形容詞",hanviet:"",ex_vi:"Phòng trống.",ex_jp:"空き部屋。",note:"⚠️trồng=植える",cat:"形容詞"},
{vi:"đông",jp:"混んでいる",pos:"形容詞",hanviet:"",ex_vi:"Đường đông.",ex_jp:"道が混んでいる。",note:"",cat:"形容詞"},
{vi:"vắng",jp:"閑散・不在",pos:"形容詞",hanviet:"",ex_vi:"Quán vắng.",ex_jp:"店が空いている。",note:"",cat:"形容詞"},
{vi:"giàu",jp:"裕福",pos:"形容詞",hanviet:"",ex_vi:"Người giàu.",ex_jp:"金持ち。",note:"",cat:"形容詞"},
{vi:"nghèo",jp:"貧乏",pos:"形容詞",hanviet:"",ex_vi:"Gia đình nghèo.",ex_jp:"貧しい家庭。",note:"",cat:"形容詞"},
{vi:"nhẹ",jp:"軽い",pos:"形容詞",hanviet:"",ex_vi:"Hành lý nhẹ.",ex_jp:"荷物が軽い。",note:"",cat:"形容詞"},
{vi:"nặng",jp:"重い",pos:"形容詞",hanviet:"",ex_vi:"Bao nặng.",ex_jp:"袋が重い。",note:"⚠️nắng=晴れ",cat:"形容詞"},
{vi:"mạnh",jp:"強い",pos:"形容詞",hanviet:"",ex_vi:"Sức mạnh.",ex_jp:"力強さ。",note:"",cat:"形容詞"},
{vi:"yếu",jp:"弱い",pos:"形容詞",hanviet:"",ex_vi:"Sức yếu.",ex_jp:"力が弱い。",note:"",cat:"形容詞"},
{vi:"cao",jp:"高い",pos:"形容詞",hanviet:"高",ex_vi:"Núi cao.",ex_jp:"高い山。",note:"",cat:"形容詞"},
{vi:"thấp",jp:"低い",pos:"形容詞",hanviet:"",ex_vi:"Bàn thấp.",ex_jp:"低い机。",note:"",cat:"形容詞"},
{vi:"sâu",jp:"深い",pos:"形容詞",hanviet:"",ex_vi:"Hồ sâu.",ex_jp:"深い湖。",note:"",cat:"形容詞"},
{vi:"cạn",jp:"浅い",pos:"形容詞",hanviet:"",ex_vi:"Sông cạn.",ex_jp:"浅い川。",note:"",cat:"形容詞"},
{vi:"giỏi",jp:"上手・優秀",pos:"形容詞",hanviet:"",ex_vi:"Học giỏi.",ex_jp:"勉強ができる。",note:"",cat:"形容詞"},
{vi:"kém",jp:"下手・劣る",pos:"形容詞",hanviet:"",ex_vi:"Tiếng Anh kém.",ex_jp:"英語が下手。",note:"",cat:"形容詞"},
{vi:"thuận tiện",jp:"便利",pos:"形容詞",hanviet:"順便",ex_vi:"Vị trí thuận tiện.",ex_jp:"便利な場所。",note:"",cat:"形容詞"},
{vi:"bất tiện",jp:"不便",pos:"形容詞",hanviet:"不便",ex_vi:"Bất tiện cho khách.",ex_jp:"客に不便。",note:"",cat:"形容詞"},
{vi:"an toàn",jp:"安全",pos:"形容詞",hanviet:"安全",ex_vi:"Lái xe an toàn.",ex_jp:"安全運転。",note:"",cat:"形容詞"},
{vi:"nguy hiểm",jp:"危険",pos:"形容詞",hanviet:"危険",ex_vi:"Đường nguy hiểm.",ex_jp:"危険な道。",note:"",cat:"形容詞"},
{vi:"thật",jp:"本当の",pos:"形容詞",hanviet:"",ex_vi:"Chuyện thật.",ex_jp:"本当の話。",note:"",cat:"形容詞"},
{vi:"giả",jp:"偽の",pos:"形容詞",hanviet:"",ex_vi:"Tiền giả.",ex_jp:"偽札。",note:"",cat:"形容詞"},
{vi:"rảnh",jp:"暇な",pos:"形容詞",hanviet:"",ex_vi:"Hôm nay rảnh.",ex_jp:"今日は暇。",note:"",cat:"形容詞"},
{vi:"bận",jp:"忙しい",pos:"形容詞",hanviet:"",ex_vi:"Tôi bận.",ex_jp:"忙しい。",note:"",cat:"形容詞"},

// === 18. 副詞・接続詞 (25) ===
{vi:"rất",jp:"とても",pos:"副詞",hanviet:"",ex_vi:"Rất ngon.",ex_jp:"とても美味しい。",note:"",cat:"副詞・接続詞"},
{vi:"quá",jp:"〜すぎる",pos:"副詞",hanviet:"",ex_vi:"Đắt quá.",ex_jp:"高すぎる。",note:"",cat:"副詞・接続詞"},
{vi:"hơi",jp:"ちょっと",pos:"副詞",hanviet:"",ex_vi:"Hơi nóng.",ex_jp:"ちょっと暑い。",note:"",cat:"副詞・接続詞"},
{vi:"khá",jp:"かなり",pos:"副詞",hanviet:"",ex_vi:"Khá tốt.",ex_jp:"かなり良い。",note:"",cat:"副詞・接続詞"},
{vi:"chỉ",jp:"〜だけ",pos:"副詞",hanviet:"",ex_vi:"Chỉ một lần.",ex_jp:"一度だけ。",note:"",cat:"副詞・接続詞"},
{vi:"cũng",jp:"〜も",pos:"副詞",hanviet:"",ex_vi:"Tôi cũng đi.",ex_jp:"私も行く。",note:"⚠️cùng=一緒に",cat:"副詞・接続詞"},
{vi:"vẫn",jp:"まだ・依然として",pos:"副詞",hanviet:"",ex_vi:"Vẫn đang học.",ex_jp:"まだ勉強中。",note:"",cat:"副詞・接続詞"},
{vi:"đã",jp:"もう・〜した",pos:"副詞",hanviet:"",ex_vi:"Đã ăn rồi.",ex_jp:"もう食べた。",note:"",cat:"副詞・接続詞"},
{vi:"đang",jp:"〜している",pos:"副詞",hanviet:"",ex_vi:"Đang làm việc.",ex_jp:"仕事中。",note:"",cat:"副詞・接続詞"},
{vi:"sẽ",jp:"〜するだろう",pos:"副詞",hanviet:"",ex_vi:"Sẽ đến.",ex_jp:"来ます。",note:"",cat:"副詞・接続詞"},
{vi:"và",jp:"〜と",pos:"接続詞",hanviet:"",ex_vi:"Anh và tôi.",ex_jp:"あなたと私。",note:"",cat:"副詞・接続詞"},
{vi:"hoặc",jp:"〜または",pos:"接続詞",hanviet:"或",ex_vi:"Cà phê hoặc trà.",ex_jp:"コーヒーかお茶。",note:"",cat:"副詞・接続詞"},
{vi:"nhưng",jp:"しかし",pos:"接続詞",hanviet:"",ex_vi:"Mệt nhưng vui.",ex_jp:"疲れたが楽しい。",note:"",cat:"副詞・接続詞"},
{vi:"vì",jp:"〜なので",pos:"接続詞",hanviet:"",ex_vi:"Vì mưa nên không đi.",ex_jp:"雨だから行かない。",note:"",cat:"副詞・接続詞"},
{vi:"nên",jp:"〜したら良い・だから",pos:"接続詞",hanviet:"",ex_vi:"Nên uống thuốc.",ex_jp:"薬を飲んだ方がいい。",note:"",cat:"副詞・接続詞"},
{vi:"nếu",jp:"もし",pos:"接続詞",hanviet:"",ex_vi:"Nếu có thời gian.",ex_jp:"もし時間があれば。",note:"",cat:"副詞・接続詞"},
{vi:"thì",jp:"〜なら",pos:"接続詞",hanviet:"",ex_vi:"Nếu có thì cho.",ex_jp:"あればあげる。",note:"",cat:"副詞・接続詞"},
{vi:"mặc dù",jp:"〜けれども",pos:"接続詞",hanviet:"黙如",ex_vi:"Mặc dù mệt.",ex_jp:"疲れているけれども。",note:"",cat:"副詞・接続詞"},
{vi:"để",jp:"〜のために",pos:"前置詞",hanviet:"",ex_vi:"Học để thi.",ex_jp:"試験のため学ぶ。",note:"",cat:"副詞・接続詞"},
{vi:"với",jp:"〜と一緒に",pos:"前置詞",hanviet:"",ex_vi:"Đi với bạn.",ex_jp:"友達と行く。",note:"",cat:"副詞・接続詞"},
{vi:"trong",jp:"〜の中",pos:"前置詞",hanviet:"",ex_vi:"Trong nhà.",ex_jp:"家の中。",note:"",cat:"副詞・接続詞"},
{vi:"ngoài",jp:"〜の外",pos:"前置詞",hanviet:"",ex_vi:"Ngoài trời.",ex_jp:"屋外。",note:"",cat:"副詞・接続詞"},
{vi:"trên",jp:"〜の上",pos:"前置詞",hanviet:"",ex_vi:"Trên bàn.",ex_jp:"机の上。",note:"",cat:"副詞・接続詞"},
{vi:"dưới",jp:"〜の下",pos:"前置詞",hanviet:"",ex_vi:"Dưới ghế.",ex_jp:"椅子の下。",note:"",cat:"副詞・接続詞"},
{vi:"cạnh",jp:"〜の隣",pos:"前置詞",hanviet:"",ex_vi:"Cạnh nhà.",ex_jp:"家の隣。",note:"",cat:"副詞・接続詞"},

// === 19. 社会・経済 (40) ===
{vi:"chính phủ",jp:"政府",pos:"名詞",hanviet:"政府",ex_vi:"Chính phủ Việt Nam.",ex_jp:"ベトナム政府。",note:"",cat:"社会・経済"},
{vi:"nhà nước",jp:"国家",pos:"名詞",hanviet:"",ex_vi:"Cơ quan nhà nước.",ex_jp:"国家機関。",note:"",cat:"社会・経済"},
{vi:"pháp luật",jp:"法律",pos:"名詞",hanviet:"法律",ex_vi:"Pháp luật Việt Nam.",ex_jp:"ベトナムの法律。",note:"",cat:"社会・経済"},
{vi:"xã hội",jp:"社会",pos:"名詞",hanviet:"社会",ex_vi:"Xã hội hiện đại.",ex_jp:"現代社会。",note:"",cat:"社会・経済"},
{vi:"kinh tế",jp:"経済",pos:"名詞",hanviet:"経済",ex_vi:"Kinh tế phát triển.",ex_jp:"経済が発展する。",note:"",cat:"社会・経済"},
{vi:"chính trị",jp:"政治",pos:"名詞",hanviet:"政治",ex_vi:"Chính trị ổn định.",ex_jp:"政治は安定。",note:"",cat:"社会・経済"},
{vi:"văn hóa",jp:"文化",pos:"名詞",hanviet:"文化",ex_vi:"Văn hóa Việt Nam.",ex_jp:"ベトナム文化。",note:"",cat:"社会・経済"},
{vi:"giáo dục",jp:"教育",pos:"名詞",hanviet:"教育",ex_vi:"Hệ thống giáo dục.",ex_jp:"教育システム。",note:"",cat:"社会・経済"},
{vi:"y tế",jp:"医療",pos:"名詞",hanviet:"医済",ex_vi:"Y tế công cộng.",ex_jp:"公衆衛生。",note:"",cat:"社会・経済"},
{vi:"bảo hiểm",jp:"保険",pos:"名詞",hanviet:"保険",ex_vi:"Bảo hiểm y tế.",ex_jp:"健康保険。",note:"",cat:"社会・経済"},
{vi:"thuế",jp:"税金",pos:"名詞",hanviet:"税",ex_vi:"Đóng thuế.",ex_jp:"税金を払う。",note:"⚠️thuê=借りる",cat:"社会・経済"},
{vi:"giá cả",jp:"価格",pos:"名詞",hanviet:"価-",ex_vi:"Giá cả tăng.",ex_jp:"物価が上がる。",note:"",cat:"社会・経済"},
{vi:"lãi suất",jp:"金利",pos:"名詞",hanviet:"利率",ex_vi:"Lãi suất thấp.",ex_jp:"金利が低い。",note:"",cat:"社会・経済"},
{vi:"đầu tư",jp:"投資",pos:"名詞",hanviet:"投資",ex_vi:"Đầu tư nước ngoài.",ex_jp:"海外投資。",note:"⚠️đầu=頭",cat:"社会・経済"},
{vi:"sản xuất",jp:"生産",pos:"動詞-動作",hanviet:"産出",ex_vi:"Sản xuất sản phẩm.",ex_jp:"製品を生産。",note:"",cat:"社会・経済"},
{vi:"tiêu thụ",jp:"消費",pos:"動詞-動作",hanviet:"消費",ex_vi:"Tiêu thụ năng lượng.",ex_jp:"エネルギーを消費。",note:"",cat:"社会・経済"},
{vi:"xuất khẩu",jp:"輸出",pos:"動詞-動作",hanviet:"出口",ex_vi:"Xuất khẩu cà phê.",ex_jp:"コーヒーを輸出。",note:"",cat:"社会・経済"},
{vi:"nhập khẩu",jp:"輸入",pos:"動詞-動作",hanviet:"入口",ex_vi:"Nhập khẩu xe ô tô.",ex_jp:"自動車を輸入。",note:"",cat:"社会・経済"},
{vi:"phát triển",jp:"発展する",pos:"動詞-動作",hanviet:"発展",ex_vi:"Kinh tế phát triển.",ex_jp:"経済が発展。",note:"",cat:"社会・経済"},
{vi:"nghiên cứu",jp:"研究",pos:"動詞-動作",hanviet:"研究",ex_vi:"Nghiên cứu khoa học.",ex_jp:"科学研究。",note:"",cat:"社会・経済"},
{vi:"công nghệ",jp:"技術・テクノロジー",pos:"名詞",hanviet:"工芸",ex_vi:"Công nghệ thông tin.",ex_jp:"IT技術。",note:"",cat:"社会・経済"},
{vi:"khoa học",jp:"科学",pos:"名詞",hanviet:"科学",ex_vi:"Tiến bộ khoa học.",ex_jp:"科学の進歩。",note:"",cat:"社会・経済"},
{vi:"môi trường",jp:"環境",pos:"名詞",hanviet:"環境",ex_vi:"Bảo vệ môi trường.",ex_jp:"環境保護。",note:"",cat:"社会・経済"},
{vi:"dân số",jp:"人口",pos:"名詞",hanviet:"民数",ex_vi:"Dân số Việt Nam.",ex_jp:"ベトナムの人口。",note:"",cat:"社会・経済"},
{vi:"thanh niên",jp:"若者",pos:"名詞",hanviet:"青年",ex_vi:"Thanh niên Việt Nam.",ex_jp:"ベトナムの若者。",note:"",cat:"社会・経済"},
{vi:"trẻ em",jp:"子供",pos:"名詞",hanviet:"-",ex_vi:"Bảo vệ trẻ em.",ex_jp:"子供を守る。",note:"",cat:"社会・経済"},
{vi:"người già",jp:"老人",pos:"名詞",hanviet:"",ex_vi:"Chăm sóc người già.",ex_jp:"老人介護。",note:"",cat:"社会・経済"},
{vi:"nông nghiệp",jp:"農業",pos:"名詞",hanviet:"農業",ex_vi:"Nông nghiệp truyền thống.",ex_jp:"伝統農業。",note:"",cat:"社会・経済"},
{vi:"công nghiệp",jp:"工業",pos:"名詞",hanviet:"工業",ex_vi:"Công nghiệp nhẹ.",ex_jp:"軽工業。",note:"",cat:"社会・経済"},
{vi:"du lịch",jp:"観光",pos:"名詞",hanviet:"遊歴",ex_vi:"Ngành du lịch.",ex_jp:"観光業。",note:"",cat:"社会・経済"},
{vi:"chiến tranh",jp:"戦争",pos:"名詞",hanviet:"戦争",ex_vi:"Sau chiến tranh.",ex_jp:"戦後。",note:"",cat:"社会・経済"},
{vi:"hòa bình",jp:"平和",pos:"名詞",hanviet:"和平",ex_vi:"Yêu hòa bình.",ex_jp:"平和を愛する。",note:"",cat:"社会・経済"},
{vi:"tự do",jp:"自由",pos:"名詞",hanviet:"自由",ex_vi:"Quyền tự do.",ex_jp:"自由の権利。",note:"",cat:"社会・経済"},
{vi:"dân chủ",jp:"民主",pos:"名詞",hanviet:"民主",ex_vi:"Xã hội dân chủ.",ex_jp:"民主社会。",note:"",cat:"社会・経済"},
{vi:"luật sư",jp:"弁護士",pos:"名詞",hanviet:"律士",ex_vi:"Thuê luật sư.",ex_jp:"弁護士を雇う。",note:"",cat:"社会・経済"},
{vi:"cảnh sát",jp:"警察",pos:"名詞",hanviet:"警察",ex_vi:"Gọi cảnh sát.",ex_jp:"警察を呼ぶ。",note:"",cat:"社会・経済"},
{vi:"tội phạm",jp:"犯罪",pos:"名詞",hanviet:"罪犯",ex_vi:"Tội phạm gia tăng.",ex_jp:"犯罪が増加。",note:"",cat:"社会・経済"},
{vi:"thị trường",jp:"市場",pos:"名詞",hanviet:"市場",ex_vi:"Thị trường mở.",ex_jp:"開かれた市場。",note:"",cat:"社会・経済"},
{vi:"cạnh tranh",jp:"競争",pos:"名詞",hanviet:"競争",ex_vi:"Cạnh tranh thị trường.",ex_jp:"市場競争。",note:"",cat:"社会・経済"},
{vi:"hợp tác",jp:"協力",pos:"名詞",hanviet:"合作",ex_vi:"Hợp tác quốc tế.",ex_jp:"国際協力。",note:"",cat:"社会・経済"},

// === 20. 漢越語(厳選) (50) ===
{vi:"quốc gia",jp:"国家",pos:"名詞",hanviet:"国家",ex_vi:"Quốc gia phát triển.",ex_jp:"発展国。",note:"",cat:"漢越語"},
{vi:"dân tộc",jp:"民族",pos:"名詞",hanviet:"民族",ex_vi:"54 dân tộc Việt Nam.",ex_jp:"ベトナム54民族。",note:"",cat:"漢越語"},
{vi:"thế giới",jp:"世界",pos:"名詞",hanviet:"世界",ex_vi:"Toàn thế giới.",ex_jp:"全世界。",note:"",cat:"漢越語"},
{vi:"thiên nhiên",jp:"自然(名詞)",pos:"名詞",hanviet:"天然",ex_vi:"Bảo vệ thiên nhiên.",ex_jp:"自然を守る。",note:"",cat:"漢越語"},
{vi:"truyền thống",jp:"伝統",pos:"名詞",hanviet:"伝統",ex_vi:"Truyền thống dân tộc.",ex_jp:"民族の伝統。",note:"",cat:"漢越語"},
{vi:"hiện đại",jp:"現代・モダン",pos:"形容詞",hanviet:"現代",ex_vi:"Cuộc sống hiện đại.",ex_jp:"現代の生活。",note:"",cat:"漢越語"},
{vi:"tự nhiên",jp:"自然な",pos:"形容詞",hanviet:"自然",ex_vi:"Vẻ tự nhiên.",ex_jp:"自然な様子。",note:"",cat:"漢越語"},
{vi:"đồng nhất",jp:"同一の",pos:"形容詞",hanviet:"同一",ex_vi:"Quan điểm đồng nhất.",ex_jp:"同じ観点。",note:"",cat:"漢越語"},
{vi:"phương pháp",jp:"方法",pos:"名詞",hanviet:"方法",ex_vi:"Phương pháp học.",ex_jp:"学習方法。",note:"",cat:"漢越語"},
{vi:"phương tiện",jp:"手段",pos:"名詞",hanviet:"方便",ex_vi:"Phương tiện giao thông.",ex_jp:"交通手段。",note:"",cat:"漢越語"},
{vi:"mục đích",jp:"目的",pos:"名詞",hanviet:"目的",ex_vi:"Mục đích cuộc đời.",ex_jp:"人生の目的。",note:"",cat:"漢越語"},
{vi:"mục tiêu",jp:"目標",pos:"名詞",hanviet:"目標",ex_vi:"Đặt mục tiêu.",ex_jp:"目標を設定。",note:"",cat:"漢越語"},
{vi:"kết quả",jp:"結果",pos:"名詞",hanviet:"結果",ex_vi:"Kết quả tốt.",ex_jp:"良い結果。",note:"",cat:"漢越語"},
{vi:"nguyên nhân",jp:"原因",pos:"名詞",hanviet:"原因",ex_vi:"Tìm nguyên nhân.",ex_jp:"原因を探す。",note:"",cat:"漢越語"},
{vi:"hiệu quả",jp:"効果",pos:"名詞",hanviet:"効果",ex_vi:"Hiệu quả cao.",ex_jp:"高い効果。",note:"",cat:"漢越語"},
{vi:"ảnh hưởng",jp:"影響",pos:"名詞",hanviet:"影響",ex_vi:"Ảnh hưởng lớn.",ex_jp:"大きな影響。",note:"",cat:"漢越語"},
{vi:"trách nhiệm",jp:"責任",pos:"名詞",hanviet:"責任",ex_vi:"Có trách nhiệm.",ex_jp:"責任がある。",note:"",cat:"漢越語"},
{vi:"nghĩa vụ",jp:"義務",pos:"名詞",hanviet:"義務",ex_vi:"Nghĩa vụ công dân.",ex_jp:"市民の義務。",note:"",cat:"漢越語"},
{vi:"quyền lợi",jp:"権利",pos:"名詞",hanviet:"権利",ex_vi:"Quyền lợi của người lao động.",ex_jp:"労働者の権利。",note:"",cat:"漢越語"},
{vi:"kinh nghiệm",jp:"経験",pos:"名詞",hanviet:"経験",ex_vi:"Kinh nghiệm làm việc.",ex_jp:"職務経験。",note:"",cat:"漢越語"},
{vi:"khả năng",jp:"可能性・能力",pos:"名詞",hanviet:"可能",ex_vi:"Có khả năng.",ex_jp:"可能性がある。",note:"",cat:"漢越語"},
{vi:"năng lực",jp:"能力",pos:"名詞",hanviet:"能力",ex_vi:"Năng lực ngoại ngữ.",ex_jp:"外国語能力。",note:"",cat:"漢越語"},
{vi:"chuyên môn",jp:"専門",pos:"名詞",hanviet:"専門",ex_vi:"Chuyên môn cao.",ex_jp:"高い専門性。",note:"",cat:"漢越語"},
{vi:"kiến thức",jp:"知識",pos:"名詞",hanviet:"見識",ex_vi:"Kiến thức rộng.",ex_jp:"広い知識。",note:"",cat:"漢越語"},
{vi:"trình độ",jp:"レベル・程度",pos:"名詞",hanviet:"程度",ex_vi:"Trình độ cao.",ex_jp:"高レベル。",note:"",cat:"漢越語"},
{vi:"chất lượng",jp:"品質",pos:"名詞",hanviet:"質量",ex_vi:"Chất lượng tốt.",ex_jp:"良い品質。",note:"",cat:"漢越語"},
{vi:"số lượng",jp:"数量",pos:"名詞",hanviet:"数量",ex_vi:"Số lượng nhiều.",ex_jp:"数量が多い。",note:"",cat:"漢越語"},
{vi:"đặc điểm",jp:"特徴",pos:"名詞",hanviet:"特点",ex_vi:"Đặc điểm chính.",ex_jp:"主な特徴。",note:"",cat:"漢越語"},
{vi:"ưu điểm",jp:"長所",pos:"名詞",hanviet:"優点",ex_vi:"Ưu điểm và nhược điểm.",ex_jp:"長所と短所。",note:"",cat:"漢越語"},
{vi:"khuyết điểm",jp:"欠点",pos:"名詞",hanviet:"欠点",ex_vi:"Khuyết điểm cần sửa.",ex_jp:"直すべき欠点。",note:"",cat:"漢越語"},
{vi:"vấn đề",jp:"問題",pos:"名詞",hanviet:"問題",ex_vi:"Giải quyết vấn đề.",ex_jp:"問題を解決。",note:"",cat:"漢越語"},
{vi:"giải pháp",jp:"解決策",pos:"名詞",hanviet:"解法",ex_vi:"Tìm giải pháp.",ex_jp:"解決策を探す。",note:"",cat:"漢越語"},
{vi:"sự kiện",jp:"イベント",pos:"名詞",hanviet:"事件",ex_vi:"Sự kiện lớn.",ex_jp:"大きなイベント。",note:"",cat:"漢越語"},
{vi:"hiện tượng",jp:"現象",pos:"名詞",hanviet:"現象",ex_vi:"Hiện tượng lạ.",ex_jp:"珍しい現象。",note:"",cat:"漢越語"},
{vi:"tình hình",jp:"状況",pos:"名詞",hanviet:"情形",ex_vi:"Tình hình kinh tế.",ex_jp:"経済状況。",note:"",cat:"漢越語"},
{vi:"tình trạng",jp:"状態",pos:"名詞",hanviet:"情状",ex_vi:"Tình trạng sức khỏe.",ex_jp:"健康状態。",note:"",cat:"漢越語"},
{vi:"giá trị",jp:"価値",pos:"名詞",hanviet:"価値",ex_vi:"Giá trị văn hóa.",ex_jp:"文化的価値。",note:"",cat:"漢越語"},
{vi:"tinh thần",jp:"精神",pos:"名詞",hanviet:"精神",ex_vi:"Tinh thần làm việc.",ex_jp:"労働精神。",note:"",cat:"漢越語"},
{vi:"thái độ",jp:"態度",pos:"名詞",hanviet:"態度",ex_vi:"Thái độ tích cực.",ex_jp:"積極的態度。",note:"",cat:"漢越語"},
{vi:"hành động",jp:"行動",pos:"名詞",hanviet:"行動",ex_vi:"Hành động dũng cảm.",ex_jp:"勇敢な行動。",note:"",cat:"漢越語"},
{vi:"ý kiến",jp:"意見",pos:"名詞",hanviet:"意見",ex_vi:"Ý kiến của tôi.",ex_jp:"私の意見。",note:"",cat:"漢越語"},
{vi:"ý nghĩa",jp:"意味",pos:"名詞",hanviet:"意義",ex_vi:"Ý nghĩa quan trọng.",ex_jp:"重要な意味。",note:"",cat:"漢越語"},
{vi:"quan điểm",jp:"観点",pos:"名詞",hanviet:"観点",ex_vi:"Quan điểm khác nhau.",ex_jp:"違う観点。",note:"",cat:"漢越語"},
{vi:"quan hệ",jp:"関係",pos:"名詞",hanviet:"関係",ex_vi:"Quan hệ tốt.",ex_jp:"良い関係。",note:"",cat:"漢越語"},
{vi:"hợp tác",jp:"協力",pos:"動詞-動作",hanviet:"合作",ex_vi:"Hợp tác công việc.",ex_jp:"仕事の協力。",note:"",cat:"漢越語"},
{vi:"thành công",jp:"成功",pos:"動詞-動作",hanviet:"成功",ex_vi:"Thành công lớn.",ex_jp:"大きな成功。",note:"",cat:"漢越語"},
{vi:"thất bại",jp:"失敗",pos:"動詞-動作",hanviet:"失敗",ex_vi:"Tránh thất bại.",ex_jp:"失敗を避ける。",note:"",cat:"漢越語"},
{vi:"phát minh",jp:"発明",pos:"動詞-動作",hanviet:"発明",ex_vi:"Phát minh mới.",ex_jp:"新発明。",note:"",cat:"漢越語"},
{vi:"sáng tạo",jp:"創造",pos:"動詞-動作",hanviet:"創造",ex_vi:"Tư duy sáng tạo.",ex_jp:"創造的思考。",note:"",cat:"漢越語"},
{vi:"phát triển",jp:"発展する",pos:"動詞-動作",hanviet:"発展",ex_vi:"Phát triển bền vững.",ex_jp:"持続可能な発展。",note:"",cat:"漢越語"}
];
