// 4級語彙データ (既存Hub/Cloud/Study/4級対策/anki_import.csvより)
// タイピング用: 日本語(jp) → ベトナム語(vi)
// note: 注釈 (混同注意・漢越対応など)
var VOCAB_4KYU = [
// 身体
{vi:"đầu",jp:"頭",note:"⚠️đầu tư=投資",cat:"身体"},
{vi:"tóc",jp:"髪",note:"",cat:"身体"},
{vi:"mặt",jp:"顔",note:"",cat:"身体"},
{vi:"mắt",jp:"目",note:"⚠️mất=無くす と混同",cat:"身体"},
{vi:"mũi",jp:"鼻",note:"",cat:"身体"},
{vi:"miệng",jp:"口",note:"",cat:"身体"},
{vi:"môi",jp:"唇",note:"",cat:"身体"},
{vi:"răng",jp:"歯",note:"",cat:"身体"},
{vi:"lưỡi",jp:"舌",note:"",cat:"身体"},
{vi:"tai",jp:"耳",note:"⚠️tai nạn=事故",cat:"身体"},
{vi:"cổ",jp:"首",note:"",cat:"身体"},
{vi:"vai",jp:"肩",note:"",cat:"身体"},
{vi:"lưng",jp:"背中",note:"",cat:"身体"},
{vi:"ngực",jp:"胸",note:"",cat:"身体"},
{vi:"bụng",jp:"お腹",note:"",cat:"身体"},
{vi:"tay",jp:"手・腕",note:"",cat:"身体"},
{vi:"chân",jp:"足",note:"",cat:"身体"},
{vi:"ngón tay",jp:"指",note:"",cat:"身体"},
{vi:"da",jp:"皮膚",note:"",cat:"身体"},
{vi:"xương",jp:"骨",note:"",cat:"身体"},
{vi:"máu",jp:"血",note:"",cat:"身体"},
{vi:"tim",jp:"心臓",note:"",cat:"身体"},
{vi:"phổi",jp:"肺",note:"",cat:"身体"},
{vi:"dạ dày",jp:"胃",note:"",cat:"身体"},
{vi:"gan",jp:"肝臓",note:"",cat:"身体"},
{vi:"não",jp:"脳",note:"",cat:"身体"},
{vi:"thận",jp:"腎臓",note:"",cat:"身体"},
{vi:"ruột",jp:"腸",note:"",cat:"身体"},
// 健康
{vi:"sức khỏe",jp:"健康",note:"漢: 力康",cat:"健康"},
{vi:"bệnh",jp:"病気",note:"",cat:"健康"},
{vi:"bệnh viện",jp:"病院",note:"漢: 病院",cat:"健康"},
{vi:"bác sĩ",jp:"医者",note:"漢: 博士",cat:"健康"},
{vi:"y tá",jp:"看護師",note:"漢: 医士",cat:"健康"},
{vi:"nha sĩ",jp:"歯科医",note:"漢: 牙士",cat:"健康"},
{vi:"thuốc",jp:"薬",note:"",cat:"健康"},
{vi:"đơn thuốc",jp:"処方箋",note:"",cat:"健康"},
{vi:"nhà thuốc",jp:"薬局",note:"",cat:"健康"},
{vi:"viên thuốc",jp:"錠剤",note:"",cat:"健康"},
{vi:"tiêm",jp:"注射",note:"",cat:"健康"},
{vi:"khám",jp:"診察する",note:"",cat:"健康"},
{vi:"chữa bệnh",jp:"治療する",note:"",cat:"健康"},
{vi:"phẫu thuật",jp:"手術",note:"",cat:"健康"},
{vi:"đau",jp:"痛い",note:"",cat:"健康"},
{vi:"nhức",jp:"ずきずき痛む",note:"",cat:"健康"},
{vi:"sốt",jp:"発熱",note:"",cat:"健康"},
{vi:"ho",jp:"咳",note:"",cat:"健康"},
{vi:"cảm",jp:"風邪",note:"",cat:"健康"},
{vi:"cảm cúm",jp:"インフルエンザ",note:"",cat:"健康"},
{vi:"dị ứng",jp:"アレルギー",note:"",cat:"健康"},
{vi:"chóng mặt",jp:"めまい",note:"",cat:"健康"},
{vi:"buồn nôn",jp:"吐き気",note:"",cat:"健康"},
{vi:"tiêu chảy",jp:"下痢",note:"",cat:"健康"},
{vi:"táo bón",jp:"便秘",note:"",cat:"健康"},
{vi:"mệt mỏi",jp:"疲れる",note:"",cat:"健康"},
{vi:"kiệt sức",jp:"疲労困憊",note:"",cat:"健康"},
{vi:"béo phì",jp:"肥満",note:"",cat:"健康"},
{vi:"gầy",jp:"痩せる",note:"",cat:"健康"},
{vi:"nằm viện",jp:"入院する",note:"",cat:"健康"},
{vi:"ra viện",jp:"退院する",note:"",cat:"健康"},
{vi:"hồi phục",jp:"回復する",note:"",cat:"健康"},
{vi:"ung thư",jp:"癌",note:"",cat:"健康"},
{vi:"huyết áp",jp:"血圧",note:"",cat:"健康"},
{vi:"cao huyết áp",jp:"高血圧",note:"",cat:"健康"},
// 感情
{vi:"cảm thấy",jp:"感じる",note:"",cat:"感情"},
{vi:"cảm xúc",jp:"感情",note:"漢: 感触",cat:"感情"},
{vi:"tâm trạng",jp:"気分",note:"漢: 心状",cat:"感情"},
{vi:"hạnh phúc",jp:"幸せ",note:"漢: 幸福",cat:"感情"},
{vi:"buồn bã",jp:"悲しい",note:"",cat:"感情"},
{vi:"đau khổ",jp:"苦しい",note:"漢: 痛苦",cat:"感情"},
{vi:"cô đơn",jp:"孤独",note:"漢: 孤単",cat:"感情"},
{vi:"hồi hộp",jp:"ドキドキ",note:"",cat:"感情"},
{vi:"bình tĩnh",jp:"落ち着いている",note:"漢: 平静",cat:"感情"},
{vi:"tự tin",jp:"自信がある",note:"漢: 自信",cat:"感情"},
{vi:"tự hào",jp:"誇り",note:"漢: 自豪",cat:"感情"},
{vi:"xấu hổ",jp:"恥ずかしい",note:"",cat:"感情"},
{vi:"ngại",jp:"気が引ける",note:"",cat:"感情"},
{vi:"lo lắng",jp:"心配する",note:"",cat:"感情"},
{vi:"căng thẳng",jp:"ストレス・緊張",note:"",cat:"感情"},
{vi:"thoải mái",jp:"リラックス・快適",note:"",cat:"感情"},
{vi:"hài lòng",jp:"満足",note:"漢: 懐量",cat:"感情"},
{vi:"thất vọng",jp:"失望",note:"漢: 失望",cat:"感情"},
{vi:"chán",jp:"うんざり",note:"",cat:"感情"},
{vi:"buồn chán",jp:"退屈",note:"",cat:"感情"},
{vi:"ngạc nhiên",jp:"驚く",note:"漢: 愕然",cat:"感情"},
{vi:"bất ngờ",jp:"予想外",note:"漢: 不期",cat:"感情"},
{vi:"tức giận",jp:"怒る",note:"",cat:"感情"},
{vi:"bực mình",jp:"イライラする",note:"",cat:"感情"},
{vi:"khó chịu",jp:"不快",note:"",cat:"感情"},
{vi:"tội nghiệp",jp:"気の毒",note:"",cat:"感情"},
{vi:"đồng cảm",jp:"共感",note:"漢: 同感",cat:"感情"},
{vi:"yêu thương",jp:"愛する",note:"",cat:"感情"},
{vi:"ghét",jp:"嫌い",note:"",cat:"感情"},
{vi:"sợ hãi",jp:"恐怖",note:"",cat:"感情"},
{vi:"lo sợ",jp:"心配で恐れる",note:"",cat:"感情"},
{vi:"tin tưởng",jp:"信頼する",note:"漢: 信想",cat:"感情"},
{vi:"nghi ngờ",jp:"疑う",note:"漢: 疑偶",cat:"感情"},
{vi:"hy vọng",jp:"希望",note:"漢: 希望",cat:"感情"},
{vi:"mong đợi",jp:"期待",note:"",cat:"感情"},
{vi:"thất bại",jp:"失敗",note:"",cat:"感情"},
{vi:"thành công",jp:"成功",note:"",cat:"感情"},
{vi:"hối hận",jp:"後悔",note:"漢: 悔恨",cat:"感情"},
{vi:"nhớ nhà",jp:"ホームシック",note:"",cat:"感情"},
// 自然
{vi:"thời tiết",jp:"天気",note:"漢: 時節",cat:"自然"},
{vi:"khí hậu",jp:"気候",note:"",cat:"自然"},
{vi:"nhiệt độ",jp:"気温",note:"",cat:"自然"},
{vi:"độ ẩm",jp:"湿度",note:"",cat:"自然"},
{vi:"mặt trời",jp:"太陽",note:"",cat:"自然"},
{vi:"mặt trăng",jp:"月",note:"",cat:"自然"},
{vi:"sao",jp:"星",note:"",cat:"自然"},
{vi:"trời",jp:"空・天",note:"",cat:"自然"},
{vi:"bầu trời",jp:"天空",note:"",cat:"自然"},
{vi:"mây",jp:"雲",note:"",cat:"自然"},
{vi:"mưa",jp:"雨",note:"",cat:"自然"},
{vi:"mưa rào",jp:"にわか雨",note:"",cat:"自然"},
{vi:"mưa phùn",jp:"小雨",note:"",cat:"自然"},
{vi:"tuyết",jp:"雪",note:"⚠️tuyệt=絶対",cat:"自然"},
{vi:"gió",jp:"風",note:"",cat:"自然"},
{vi:"bão",jp:"台風",note:"",cat:"自然"},
{vi:"lũ lụt",jp:"洪水",note:"",cat:"自然"},
{vi:"động đất",jp:"地震",note:"",cat:"自然"},
{vi:"sấm",jp:"雷鳴",note:"",cat:"自然"},
{vi:"sét",jp:"稲妻",note:"",cat:"自然"},
{vi:"cầu vồng",jp:"虹",note:"",cat:"自然"},
{vi:"sương mù",jp:"霧",note:"",cat:"自然"},
{vi:"núi",jp:"山",note:"",cat:"自然"},
{vi:"đồi",jp:"丘",note:"",cat:"自然"},
{vi:"sông",jp:"川",note:"",cat:"自然"},
{vi:"hồ",jp:"湖",note:"",cat:"自然"},
{vi:"biển",jp:"海",note:"",cat:"自然"},
{vi:"bãi biển",jp:"砂浜",note:"",cat:"自然"},
{vi:"đảo",jp:"島",note:"",cat:"自然"},
{vi:"rừng",jp:"森",note:"",cat:"自然"},
{vi:"cây",jp:"木",note:"",cat:"自然"},
{vi:"lá",jp:"葉",note:"",cat:"自然"},
{vi:"hoa",jp:"花",note:"",cat:"自然"},
{vi:"cỏ",jp:"草",note:"",cat:"自然"},
{vi:"môi trường",jp:"環境",note:"",cat:"自然"},
{vi:"ô nhiễm",jp:"汚染",note:"",cat:"自然"},
{vi:"không khí",jp:"空気",note:"",cat:"自然"},
{vi:"rác",jp:"ゴミ",note:"",cat:"自然"},
{vi:"rác thải",jp:"廃棄物",note:"",cat:"自然"},
{vi:"bảo vệ",jp:"保護する",note:"",cat:"自然"},
{vi:"tiết kiệm",jp:"節約",note:"",cat:"自然"},
{vi:"năng lượng",jp:"エネルギー",note:"",cat:"自然"},
{vi:"biến đổi khí hậu",jp:"気候変動",note:"",cat:"自然"},
// 社会
{vi:"chính phủ",jp:"政府",note:"",cat:"社会"},
{vi:"nhà nước",jp:"国家",note:"",cat:"社会"},
{vi:"pháp luật",jp:"法律",note:"",cat:"社会"},
{vi:"quy định",jp:"規定",note:"",cat:"社会"},
{vi:"thuế",jp:"税金",note:"⚠️thuê=借りる",cat:"社会"},
{vi:"bảo hiểm",jp:"保険",note:"",cat:"社会"},
{vi:"bảo hiểm y tế",jp:"健康保険",note:"",cat:"社会"},
{vi:"ngân hàng",jp:"銀行",note:"",cat:"社会"},
{vi:"tài khoản",jp:"口座",note:"",cat:"社会"},
{vi:"tiền mặt",jp:"現金",note:"",cat:"社会"},
{vi:"thẻ tín dụng",jp:"クレジットカード",note:"",cat:"社会"},
{vi:"lương",jp:"給料",note:"⚠️lượng=量",cat:"社会"},
{vi:"thu nhập",jp:"収入",note:"",cat:"社会"},
{vi:"chi phí",jp:"費用",note:"",cat:"社会"},
{vi:"giá cả",jp:"価格",note:"",cat:"社会"},
{vi:"tỷ giá",jp:"為替レート",note:"",cat:"社会"},
{vi:"lãi suất",jp:"金利",note:"",cat:"社会"},
{vi:"kinh tế",jp:"経済",note:"",cat:"社会"},
{vi:"chính trị",jp:"政治",note:"",cat:"社会"},
{vi:"xã hội",jp:"社会",note:"",cat:"社会"},
{vi:"văn hóa",jp:"文化",note:"",cat:"社会"},
{vi:"giáo dục",jp:"教育",note:"",cat:"社会"},
{vi:"y tế",jp:"医療",note:"",cat:"社会"},
{vi:"công ty",jp:"会社",note:"",cat:"社会"},
{vi:"nhân viên",jp:"従業員",note:"",cat:"社会"},
{vi:"giám đốc",jp:"社長",note:"",cat:"社会"},
{vi:"đồng nghiệp",jp:"同僚",note:"",cat:"社会"},
{vi:"khách hàng",jp:"顧客",note:"",cat:"社会"},
{vi:"sản phẩm",jp:"製品",note:"",cat:"社会"},
{vi:"dịch vụ",jp:"サービス",note:"",cat:"社会"},
{vi:"thị trường",jp:"市場",note:"",cat:"社会"},
{vi:"cạnh tranh",jp:"競争",note:"",cat:"社会"},
{vi:"hợp đồng",jp:"契約",note:"",cat:"社会"},
{vi:"đầu tư",jp:"投資",note:"",cat:"社会"},
{vi:"xuất khẩu",jp:"輸出",note:"",cat:"社会"},
{vi:"nhập khẩu",jp:"輸入",note:"",cat:"社会"},
{vi:"sản xuất",jp:"生産",note:"",cat:"社会"},
{vi:"tiêu thụ",jp:"消費",note:"",cat:"社会"},
{vi:"phát triển",jp:"発展",note:"",cat:"社会"},
{vi:"quản lý",jp:"管理",note:"",cat:"社会"},
{vi:"báo cáo",jp:"報告",note:"",cat:"社会"},
{vi:"họp",jp:"会議",note:"",cat:"社会"},
{vi:"hội nghị",jp:"会議(大規模)",note:"",cat:"社会"},
{vi:"chương trình",jp:"プログラム",note:"",cat:"社会"},
{vi:"dự án",jp:"プロジェクト",note:"",cat:"社会"},
// 動詞
{vi:"bắt đầu",jp:"始める",note:"",cat:"動詞"},
{vi:"kết thúc",jp:"終わる",note:"",cat:"動詞"},
{vi:"tiếp tục",jp:"続ける",note:"",cat:"動詞"},
{vi:"dừng lại",jp:"止まる",note:"",cat:"動詞"},
{vi:"chuẩn bị",jp:"準備する",note:"",cat:"動詞"},
{vi:"hoàn thành",jp:"達成する",note:"",cat:"動詞"},
{vi:"cố gắng",jp:"努力する",note:"",cat:"動詞"},
{vi:"cải thiện",jp:"改善する",note:"",cat:"動詞"},
{vi:"thay đổi",jp:"変わる",note:"",cat:"動詞"},
{vi:"giữ gìn",jp:"維持する",note:"",cat:"動詞"},
{vi:"giải quyết",jp:"解決する",note:"",cat:"動詞"},
{vi:"tham gia",jp:"参加する",note:"",cat:"動詞"},
{vi:"tham dự",jp:"出席する",note:"",cat:"動詞"},
{vi:"tổ chức",jp:"組織する・開催する",note:"",cat:"動詞"},
{vi:"sắp xếp",jp:"整理する",note:"",cat:"動詞"},
{vi:"kiểm tra",jp:"検査する",note:"",cat:"動詞"},
{vi:"xác nhận",jp:"確認する",note:"",cat:"動詞"},
{vi:"so sánh",jp:"比較する",note:"",cat:"動詞"},
{vi:"phân biệt",jp:"区別する",note:"",cat:"動詞"},
{vi:"giới thiệu",jp:"紹介する",note:"",cat:"動詞"},
{vi:"giải thích",jp:"説明する",note:"",cat:"動詞"},
{vi:"hướng dẫn",jp:"案内する",note:"",cat:"動詞"},
{vi:"thảo luận",jp:"議論する",note:"",cat:"動詞"},
{vi:"đề nghị",jp:"提案する",note:"",cat:"動詞"},
{vi:"quyết định",jp:"決定する",note:"",cat:"動詞"},
{vi:"lựa chọn",jp:"選択する",note:"",cat:"動詞"},
{vi:"đồng ý",jp:"同意する",note:"",cat:"動詞"},
{vi:"phản đối",jp:"反対する",note:"",cat:"動詞"},
{vi:"chia sẻ",jp:"共有する",note:"",cat:"動詞"},
{vi:"thực hiện",jp:"実現する・実施する",note:"",cat:"動詞"},
{vi:"triển khai",jp:"展開する",note:"",cat:"動詞"},
{vi:"phát biểu",jp:"発表する",note:"",cat:"動詞"},
{vi:"động viên",jp:"励ます",note:"",cat:"動詞"},
{vi:"giúp đỡ",jp:"助ける",note:"",cat:"動詞"},
{vi:"cứu",jp:"救う",note:"",cat:"動詞"},
// 時間
{vi:"khoảnh khắc",jp:"瞬間",note:"",cat:"時間"},
{vi:"giây lát",jp:"ちょっと",note:"",cat:"時間"},
{vi:"hiện tại",jp:"現在",note:"",cat:"時間"},
{vi:"quá khứ",jp:"過去",note:"",cat:"時間"},
{vi:"tương lai",jp:"未来",note:"",cat:"時間"},
{vi:"gần đây",jp:"最近",note:"",cat:"時間"},
{vi:"dạo này",jp:"最近(口語)",note:"",cat:"時間"},
{vi:"ngày xưa",jp:"昔",note:"",cat:"時間"},
{vi:"ngày nay",jp:"今日では",note:"",cat:"時間"},
{vi:"hôm nọ",jp:"先日",note:"",cat:"時間"},
{vi:"lát nữa",jp:"あとで",note:"",cat:"時間"},
{vi:"sắp tới",jp:"もうすぐ",note:"",cat:"時間"},
{vi:"đúng giờ",jp:"時間通り",note:"",cat:"時間"},
{vi:"kịp giờ",jp:"間に合う",note:"",cat:"時間"},
{vi:"suốt đêm",jp:"一晩中",note:"",cat:"時間"},
{vi:"cả ngày",jp:"一日中",note:"",cat:"時間"},
{vi:"thường xuyên",jp:"頻繁に",note:"",cat:"時間"},
{vi:"liên tục",jp:"連続して",note:"",cat:"時間"},
{vi:"tạm thời",jp:"一時的",note:"",cat:"時間"},
{vi:"đồng thời",jp:"同時に",note:"",cat:"時間"},
{vi:"vĩnh viễn",jp:"永久に",note:"",cat:"時間"},
{vi:"đột nhiên",jp:"突然",note:"",cat:"時間"},
{vi:"dần dần",jp:"だんだん",note:"",cat:"時間"},
{vi:"ngay lập tức",jp:"すぐに",note:"",cat:"時間"},
{vi:"mãi mãi",jp:"永遠に",note:"",cat:"時間"},
// 漢越
{vi:"kinh doanh",jp:"ビジネス",note:"漢: 経営",cat:"漢越"},
{vi:"thương mại",jp:"商業",note:"漢: 商買",cat:"漢越"},
{vi:"luật sư",jp:"弁護士",note:"漢: 律士",cat:"漢越"},
{vi:"nghệ thuật",jp:"芸術",note:"漢: 芸術",cat:"漢越"},
{vi:"âm nhạc",jp:"音楽",note:"漢: 音楽",cat:"漢越"},
{vi:"điện ảnh",jp:"映画",note:"漢: 電影",cat:"漢越"},
{vi:"truyền hình",jp:"テレビ",note:"漢: 伝形",cat:"漢越"},
{vi:"báo chí",jp:"報道",note:"漢: 報紙",cat:"漢越"},
{vi:"giáo viên",jp:"教師",note:"漢: 教員",cat:"漢越"},
{vi:"sinh viên",jp:"大学生",note:"漢: 生員",cat:"漢越"},
{vi:"đại học",jp:"大学",note:"漢: 大学",cat:"漢越"},
{vi:"luận văn",jp:"論文",note:"漢: 論文",cat:"漢越"},
{vi:"nghiên cứu",jp:"研究",note:"漢: 研究",cat:"漢越"},
{vi:"phát minh",jp:"発明",note:"漢: 発明",cat:"漢越"},
{vi:"y học",jp:"医学",note:"漢: 医学",cat:"漢越"},
{vi:"thể thao",jp:"スポーツ",note:"漢: 体操",cat:"漢越"},
{vi:"vận động viên",jp:"アスリート",note:"漢: 運動員",cat:"漢越"},
{vi:"huấn luyện",jp:"訓練",note:"漢: 訓練",cat:"漢越"},
{vi:"thi đấu",jp:"試合",note:"漢: 試鬪",cat:"漢越"},
{vi:"chiến thắng",jp:"勝利",note:"漢: 戦勝",cat:"漢越"},
{vi:"nguy hiểm",jp:"危険",note:"漢: 危険",cat:"漢越"},
{vi:"an toàn",jp:"安全",note:"漢: 安全",cat:"漢越"},
{vi:"trách nhiệm",jp:"責任",note:"漢: 責任",cat:"漢越"},
{vi:"nghĩa vụ",jp:"義務",note:"漢: 義務",cat:"漢越"},
{vi:"quyền lợi",jp:"権利",note:"漢: 権利",cat:"漢越"},
{vi:"tự do",jp:"自由",note:"漢: 自由",cat:"漢越"},
{vi:"dân chủ",jp:"民主",note:"漢: 民主",cat:"漢越"},
{vi:"hòa bình",jp:"平和",note:"漢: 和平",cat:"漢越"},
{vi:"chiến tranh",jp:"戦争",note:"漢: 戦争",cat:"漢越"},
{vi:"thiên nhiên",jp:"自然(名詞)",note:"漢: 天然",cat:"漢越"},
{vi:"địa lý",jp:"地理",note:"漢: 地理",cat:"漢越"},
{vi:"lịch sử",jp:"歴史",note:"漢: 暦史",cat:"漢越"},
{vi:"truyền thống",jp:"伝統",note:"漢: 伝統",cat:"漢越"},
{vi:"phong tục",jp:"風習",note:"漢: 風俗",cat:"漢越"},
{vi:"tôn giáo",jp:"宗教",note:"漢: 尊教",cat:"漢越"},
{vi:"tinh thần",jp:"精神",note:"漢: 精神",cat:"漢越"},
{vi:"cơ bản",jp:"基本的",note:"漢: 基本",cat:"漢越"},
{vi:"cơ hội",jp:"機会",note:"漢: 機会",cat:"漢越"},
{vi:"kỹ thuật",jp:"技術",note:"漢: 技術",cat:"漢越"},
{vi:"công nghệ",jp:"テクノロジー",note:"漢: 工芸",cat:"漢越"},
{vi:"thông tin",jp:"情報",note:"漢: 通信",cat:"漢越"},
{vi:"giao thông",jp:"交通",note:"漢: 交通",cat:"漢越"},
{vi:"kiến trúc",jp:"建築",note:"漢: 建築",cat:"漢越"},
{vi:"kiến thức",jp:"知識",note:"漢: 見識",cat:"漢越"},
{vi:"tài sản",jp:"財産",note:"漢: 財産",cat:"漢越"},
{vi:"lãng phí",jp:"浪費",note:"漢: 浪費",cat:"漢越"},
{vi:"chất lượng",jp:"品質",note:"漢: 質量",cat:"漢越"},
{vi:"số lượng",jp:"数量",note:"漢: 数量",cat:"漢越"},
{vi:"đặc điểm",jp:"特徴",note:"漢: 特点",cat:"漢越"},
{vi:"ưu điểm",jp:"長所",note:"漢: 優点",cat:"漢越"},
{vi:"khuyết điểm",jp:"欠点",note:"漢: 欠点",cat:"漢越"},
{vi:"nguyên nhân",jp:"原因",note:"漢: 原因",cat:"漢越"},
{vi:"kết quả",jp:"結果",note:"漢: 結果",cat:"漢越"},
{vi:"hiệu quả",jp:"効果",note:"漢: 効果",cat:"漢越"},
{vi:"ảnh hưởng",jp:"影響",note:"漢: 影響",cat:"漢越"},
{vi:"quan hệ",jp:"関係",note:"漢: 関係",cat:"漢越"},
{vi:"quan trọng",jp:"重要",note:"漢: 関重",cat:"漢越"},
{vi:"đặc biệt",jp:"特別",note:"漢: 特別",cat:"漢越"},
{vi:"bình thường",jp:"普通",note:"漢: 平常",cat:"漢越"},
{vi:"tự nhiên",jp:"自然な",note:"漢: 自然",cat:"漢越"},
{vi:"tự động",jp:"自動",note:"漢: 自動",cat:"漢越"},
{vi:"ý kiến",jp:"意見",note:"漢: 意見",cat:"漢越"},
{vi:"ý nghĩa",jp:"意味",note:"漢: 意義",cat:"漢越"},
{vi:"ý thức",jp:"意識",note:"漢: 意識",cat:"漢越"},
{vi:"quan điểm",jp:"観点",note:"漢: 観点",cat:"漢越"},
{vi:"thái độ",jp:"態度",note:"漢: 態度",cat:"漢越"},
{vi:"hành động",jp:"行動",note:"漢: 行動",cat:"漢越"},
{vi:"phản ứng",jp:"反応",note:"漢: 反応",cat:"漢越"},
{vi:"hợp tác",jp:"協力",note:"漢: 合作",cat:"漢越"},
{vi:"thống nhất",jp:"統一",note:"漢: 統一",cat:"漢越"},
{vi:"độc lập",jp:"独立",note:"漢: 独立",cat:"漢越"},
{vi:"tham khảo",jp:"参考",note:"漢: 参考",cat:"漢越"},
{vi:"tập trung",jp:"集中",note:"漢: 集中",cat:"漢越"},
{vi:"gia đình",jp:"家族",note:"漢: 家庭",cat:"漢越"},
{vi:"quốc gia",jp:"国家",note:"漢: 国家",cat:"漢越"},
{vi:"dân tộc",jp:"民族",note:"漢: 民族",cat:"漢越"},
{vi:"dân số",jp:"人口",note:"漢: 民数",cat:"漢越"},
{vi:"lao động",jp:"労働",note:"漢: 労働",cat:"漢越"},
{vi:"nghề nghiệp",jp:"職業",note:"",cat:"漢越"},
{vi:"chuyên môn",jp:"専門",note:"漢: 専門",cat:"漢越"},
{vi:"năng lực",jp:"能力",note:"漢: 能力",cat:"漢越"},
{vi:"khả năng",jp:"可能性",note:"漢: 可能",cat:"漢越"},
{vi:"kinh nghiệm",jp:"経験",note:"漢: 経験",cat:"漢越"},
{vi:"trình độ",jp:"水準",note:"漢: 程度",cat:"漢越"},
{vi:"hình thức",jp:"形式",note:"漢: 形式",cat:"漢越"},
{vi:"nội dung",jp:"内容",note:"漢: 内容",cat:"漢越"},
{vi:"cấu trúc",jp:"構造",note:"漢: 構造",cat:"漢越"},
{vi:"phương pháp",jp:"方法",note:"漢: 方法",cat:"漢越"},
{vi:"phương tiện",jp:"手段",note:"漢: 方便",cat:"漢越"},
{vi:"mục đích",jp:"目的",note:"漢: 目的",cat:"漢越"},
{vi:"mục tiêu",jp:"目標",note:"漢: 目標",cat:"漢越"},
{vi:"kế hoạch",jp:"計画",note:"漢: 計画",cat:"漢越"},
{vi:"dự báo",jp:"予報",note:"漢: 予報",cat:"漢越"},
{vi:"dự định",jp:"予定",note:"漢: 予定",cat:"漢越"},
{vi:"sự kiện",jp:"イベント",note:"漢: 事件",cat:"漢越"},
{vi:"hiện tượng",jp:"現象",note:"漢: 現象",cat:"漢越"},
{vi:"tình hình",jp:"状況",note:"漢: 情形",cat:"漢越"},
{vi:"tình trạng",jp:"状態",note:"漢: 情状",cat:"漢越"},
{vi:"vấn đề",jp:"問題",note:"漢: 問題",cat:"漢越"},
{vi:"giải pháp",jp:"解決策",note:"漢: 解法",cat:"漢越"},
{vi:"cải cách",jp:"改革",note:"漢: 改革",cat:"漢越"},
{vi:"ổn định",jp:"安定",note:"漢: 穏定",cat:"漢越"},
{vi:"phát huy",jp:"発揮",note:"漢: 発揮",cat:"漢越"},
{vi:"sử dụng",jp:"使用",note:"漢: 使用",cat:"漢越"},
{vi:"ứng dụng",jp:"応用",note:"漢: 応用",cat:"漢越"},
{vi:"áp dụng",jp:"適用",note:"漢: 押用",cat:"漢越"}
];
